server:
    interface: 10.77.0.1@53
    interface: fd4b:7572:6400::1@53
    access-control: 0.0.0.0/0 refuse
    access-control: ::0/0 refuse
    access-control: 10.77.0.0/24 allow
    access-control: fd4b:7572:6400::/64 allow
    ip-freebind: yes
    do-ip4: yes
    do-ip6: yes
    do-udp: yes
    do-tcp: yes
    hide-identity: yes
    hide-version: yes
    hide-trustanchor: yes
    qname-minimisation: yes
    harden-dnssec-stripped: yes
    harden-below-nxdomain: yes
    harden-referral-path: yes
    aggressive-nsec: yes
    val-permissive-mode: no
    log-queries: no
    log-replies: no
    log-local-actions: no
    log-servfail: no
    verbosity: 1
    num-threads: 1
    outgoing-range: 256
    num-queries-per-thread: 128
    incoming-num-tcp: 32
    outgoing-num-tcp: 32
    msg-cache-size: 16m
    rrset-cache-size: 32m
    infra-cache-numhosts: 10000
    prefetch: yes
    serve-expired: no
    unwanted-reply-threshold: 10000000

remote-control:
    control-enable: no
