import {rankSearch} from '../lib/core.mjs';
import {msg} from './locale.js';
/** No query leaves this browser; result URLs are constrained to the current locale. */
export function setupSearch(){
 const dialog=document.querySelector('#site-search'),input=document.querySelector('#global-search');let index=null,pending=null,opener=null,sequence=0;
 async function load(){if(index)return index;if(!pending)pending=fetch(document.body.dataset.searchIndex,{credentials:'omit',cache:'force-cache'}).then(r=>{if(!r.ok)throw Error('Index unavailable');return r.json();}).then(data=>{if(!Array.isArray(data))throw Error('Invalid index');const base=document.body.dataset.base+document.body.dataset.locale+'/';index=data.filter(x=>typeof x.title==='string'&&typeof x.description==='string'&&typeof x.url==='string'&&x.url.startsWith(base)&&!x.url.includes('\\'));return index;}).catch(err=>{pending=null;throw err;});return pending;}
 function results(items,host){host.replaceChildren();const list=document.createElement('ul');list.className='search-results';for(const item of items.slice(0,35)){const li=document.createElement('li'),a=document.createElement('a'),cat=document.createElement('small'),title=document.createElement('strong'),description=document.createElement('p');a.className='search-result';a.href=item.url;cat.textContent=item.category;title.textContent=item.title;description.textContent=item.description;a.append(cat,title,description);li.append(a);list.append(li);}if(!items.length){const div=document.createElement('div'),h=document.createElement('strong'),p=document.createElement('p');div.className='search-empty';h.textContent=msg('No matching explanation.');p.textContent=msg('Try profile, permission, DNS or self-hosting. Nothing was submitted or changed.');div.append(h,p);host.append(div);}else host.append(list);}
 async function update(q,host,status){const n=++sequence;status.textContent=msg('Loading the local search index…');try{const data=await load();if(n!==sequence)return;const found=rankSearch(q.slice(0,120),data);results(found,host);status.textContent=msg('{count} results. Search stays on this device.',{count:new Intl.NumberFormat(document.body.dataset.locale).format(found.length)});if(found.length>35)status.textContent+=' '+msg('The first 35 are shown.');}catch{status.textContent=msg('The search index could not be loaded. Use the full search page or navigation. No query was sent.');}}
 function close(){if(dialog?.open)dialog.close();if(opener?.isConnected)opener.focus();}
 dialog?.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();event.stopPropagation();close();}});
 function open(el){if(!dialog?.showModal)return false;opener=el||document.activeElement;document.querySelectorAll('.preferences[open],.language-menu[open],.mobile-menu[open]').forEach(d=>d.open=false);dialog.showModal();input.focus();update(input.value,dialog.querySelector('[data-global-results]'),document.querySelector('#global-search-status'));return true;}
 document.querySelectorAll('[data-search-open]').forEach(a=>a.addEventListener('click',e=>{if(open(a))e.preventDefault();}));document.querySelector('[data-search-close]')?.addEventListener('click',close);dialog?.addEventListener('cancel',e=>{e.preventDefault();close();});input?.addEventListener('input',()=>update(input.value,dialog.querySelector('[data-global-results]'),document.querySelector('#global-search-status')));
 dialog?.addEventListener('keydown',e=>{const links=[...dialog.querySelectorAll('.search-result')];if(!links.length)return;if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();const i=links.indexOf(document.activeElement),next=e.key==='ArrowDown'?Math.min(i+1,links.length-1):i-1;(next<0?input:links[next]).focus();}});
 document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'&&!e.altKey){e.preventDefault();dialog?.open?close():open(document.activeElement);}});
 const pageInput=document.querySelector('#page-search');if(pageInput){const host=document.querySelector('[data-page-results]'),status=document.querySelector('#page-search-status');pageInput.addEventListener('input',()=>update(pageInput.value,host,status));try{const q=new URL(location.href).searchParams.get('q');if(q){pageInput.value=q.slice(0,120);update(pageInput.value,host,status);}}catch{}}
}
