package codegen

import (
	"bytes"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"reflect"
	"runtime"
	"sort"
	"strings"
	"testing"
	"time"

	"kurdistan/internal/protocol/compiler"
	"kurdistan/internal/protocol/ir"
)

var _ func([]byte) (AuthorizationCatalogV1, error) = ParseAuthorizationCatalogV1
var _ func(*ir.Profile, string, Options, AuthorizationCatalogV1) (Result, error) = GenerateStrict
var _ func(AuthorizationCatalogV1, string, int64, int) error = AuthorizationCatalogV1.ValidateExactSeedRangeV1

func wirePinV1(p AuthorizationPinV1) pinWireV1 {
	h := func(v [32]byte) string { return hex.EncodeToString(v[:]) }
	return pinWireV1{h(p.ProfileHash), h(p.EffectivePolicyHash), h(p.FramingHash), h(p.StateMachineHash), h(p.SchedulerHash), h(p.PaddingHash), h(p.StreamHash), h(p.ProxyHash), h(p.CarrierContextHash), p.EffectiveReplayWindow, p.EffectiveMaxConcurrentStreams, p.EffectiveMaxFrameBytes, p.EffectiveMaxEnvelopeBytes}
}
func catalogFixtureV1(t *testing.T, p *ir.Profile) AuthorizationCatalogV1 {
	t.Helper()
	pin, err := expectedPinV1(p)
	if err != nil {
		t.Fatal(err)
	}
	raw, err := json.Marshal(catalogWireV1{AuthorizationCatalogVersionV1, AuthorizationCatalogScopeExplicitV1, []entryWireV1{{p.Seed, wirePinV1(pin), wirePinV1(pin)}}})
	if err != nil {
		t.Fatal(err)
	}
	c, err := ParseAuthorizationCatalogV1(raw)
	if err != nil {
		t.Fatal(err)
	}
	return c
}

func TestAuthorizationV1CatalogAndCanonical(t *testing.T) {
	p, err := compiler.Generate(40)
	if err != nil {
		t.Fatal(err)
	}
	c := catalogFixtureV1(t, p)
	if err := c.ValidateExactSeedRangeV1(AuthorizationCatalogScopeExplicitV1, p.Seed, 1); err != nil {
		t.Fatal(err)
	}
	raw, err := c.canonical()
	if err != nil || len(raw) == 0 {
		t.Fatal(err)
	}
	if c.digest == ([32]byte{}) {
		t.Fatal("zero digest")
	}
}

func TestAuthorizationCatalogStrictJSON(t *testing.T) {
	p, _ := compiler.Generate(41)
	pin, _ := expectedPinV1(p)
	good, _ := json.Marshal(catalogWireV1{AuthorizationCatalogVersionV1, AuthorizationCatalogScopeExplicitV1, []entryWireV1{{p.Seed, wirePinV1(pin), wirePinV1(pin)}}})
	for _, raw := range [][]byte{nil, append(good, []byte(" {}")...), []byte(`{"version":"profile-authorization-catalog-v1","version":"x","scope":"explicit_v1","entries":[]}`), make([]byte, (1<<20)+1)} {
		if _, err := ParseAuthorizationCatalogV1(raw); !errors.Is(err, ErrAuthorizationCatalogInvalid) || err.Error() != ErrAuthorizationCatalogInvalid.Error() {
			t.Fatalf("err=%v", err)
		}
	}
}

func TestStrictGenerateAndManifestAuthorization(t *testing.T) {
	p, err := compiler.Generate(42)
	if err != nil {
		t.Fatal(err)
	}
	c := catalogFixtureV1(t, p)
	out := filepath.Join(t.TempDir(), "strict")
	result, err := GenerateStrict(p, out, Options{GeneratedAt: time.Unix(0, 0).UTC()}, c)
	if err != nil {
		t.Fatal(err)
	}
	if result.Manifest.AuthorizationCatalogVersion != "profile-authorization-catalog-v1" || result.Manifest.AuthorizationCatalogScope != "explicit_v1" || len(result.Manifest.AuthorizationCatalogSHA256) != 64 {
		t.Fatalf("manifest=%+v", result.Manifest)
	}
	if _, err := os.Stat(filepath.Join(out, "manifest.json")); err != nil {
		t.Fatal(err)
	}
	wrongPin, _ := expectedPinV1(p)
	wrongPin.ProfileHash[0] ^= 1
	badRaw, _ := json.Marshal(catalogWireV1{AuthorizationCatalogVersionV1, AuthorizationCatalogScopeExplicitV1, []entryWireV1{{p.Seed, wirePinV1(wrongPin), wirePinV1(wrongPin)}}})
	bad, parseErr := ParseAuthorizationCatalogV1(badRaw)
	if parseErr != nil {
		t.Fatal(parseErr)
	}
	if _, err := GenerateStrict(p, filepath.Join(t.TempDir(), "bad"), Options{}, bad); !errors.Is(err, ErrAuthorizationMismatch) {
		t.Fatal(err)
	}
	tooHigh := *p
	tooHigh.Seed = math.MaxInt64 - 6
	if _, err := GenerateStrict(&tooHigh, filepath.Join(t.TempDir(), "range"), Options{}, c); !errors.Is(err, ErrStrictSeedRange) {
		t.Fatal(err)
	}
}

func TestLegacyGenerateCompatibility(t *testing.T) {
	p, _ := compiler.Generate(43)
	out := filepath.Join(t.TempDir(), "legacy")
	result, err := Generate(p, out, Options{
		GeneratedAt: time.Unix(0, 0).UTC(),
		RepoRoot:    "/repo/kurdistan-protocol-compiler",
	})
	if err != nil {
		t.Fatal(err)
	}
	if result.Manifest.AuthorizationCatalogVersion != "" || result.Manifest.AuthorizationCatalogScope != "" || result.Manifest.AuthorizationCatalogSHA256 != "" {
		t.Fatal("legacy manifest gained authorization")
	}
	// This pins deterministic current Phase1 legacy-API output after the
	// intentional Go/schema/security version migration; it does not claim
	// pre-WO-040 byte identity.
	const currentPhase1LegacyTreeSHA256 = "22f98bb8d1f814c4a51ed8826cefa3f266774a2f95fe9b67464dafe7d60a9750"
	if got := generatedTreeDigestV1(t, out); got != currentPhase1LegacyTreeSHA256 {
		t.Fatalf("legacy generated bytes changed: got %s want %s", got, currentPhase1LegacyTreeSHA256)
	}
}

func generatedTreeDigestV1(t *testing.T, root string) string {
	t.Helper()
	var paths []string
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() {
			paths = append(paths, path)
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	sort.Strings(paths)
	h := sha256.New()
	for _, path := range paths {
		rel, err := filepath.Rel(root, path)
		if err != nil {
			t.Fatal(err)
		}
		independentLPV1BufferV1(h, []byte(filepath.ToSlash(rel)))
		b, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		independentLPV1BufferV1(h, b)
	}
	return hex.EncodeToString(h.Sum(nil))
}

type byteWriterV1 interface{ Write([]byte) (int, error) }

func independentLPV1BufferV1(out byteWriterV1, value []byte) {
	var n [4]byte
	binary.BigEndian.PutUint32(n[:], uint32(len(value)))
	_, _ = out.Write(n[:])
	_, _ = out.Write(value)
}

func TestAuthorizationV1SignedSelectors(t *testing.T) {
	for _, seed := range []int64{-1, math.MinInt64, 0, 1, 42} {
		_ = relayFleetAssignmentMode(seed)
		_ = relayFleetChurnMode(seed)
		_ = relayFleetMigrationMode(seed)
	}
}

func hardcodedHashV1(t *testing.T, s string) [32]byte {
	t.Helper()
	var out [32]byte
	b, err := hex.DecodeString(s)
	if err != nil || len(b) != 32 {
		t.Fatal(err)
	}
	copy(out[:], b)
	return out
}

func independentSeed42PinV1(t *testing.T) AuthorizationPinV1 {
	return AuthorizationPinV1{ProfileHash: hardcodedHashV1(t, "af5f7ecf37cdd21cab29a7938f73ef3d5c6be849a8fb3d4f4c5e308c9312b4e2"), EffectivePolicyHash: hardcodedHashV1(t, "9a208cab2e4393c3c6417fc1436a1a7c9959dce4a50ac435baaf5d8b72d5bad7"), FramingHash: hardcodedHashV1(t, "1e01c3b207af2122b5dff65f1945f7dbad96c288163e5deb65684e9ed297da6c"), StateMachineHash: hardcodedHashV1(t, "ccf2a4742252f71b3d4aaa5cc9c0e26f00222df81dd7c9020afb1ca6ae48489f"), SchedulerHash: hardcodedHashV1(t, "8c27f74766a072e98e7a3108c02dd1680f6381178e23323fc8422b3f5f574930"), PaddingHash: hardcodedHashV1(t, "ea3b7b093bb10a81d7a10cb21a465f022070ca1d0438683dd7b7843a4437db36"), StreamHash: hardcodedHashV1(t, "2bf26abe3667e47418a4fc935f8aeb18f64620454dd1ee234faba4ddcd9e2c90"), ProxyHash: hardcodedHashV1(t, "3e4bbe2759342669767541930cda069f9bee0b3b419c3016b64ee05621124ebd"), CarrierContextHash: hardcodedHashV1(t, "f71bd073932bf7de9a4df9dd0f666827849f9a87f895de98c5813f7474a116b2"), EffectiveReplayWindow: 128, EffectiveMaxConcurrentStreams: 8, EffectiveMaxFrameBytes: 65536, EffectiveMaxEnvelopeBytes: 8192}
}

func TestAuthorizationV1HardcodedIndependentSeed42Vector(t *testing.T) {
	p, err := compiler.Generate(42)
	if err != nil {
		t.Fatal(err)
	}
	want := independentSeed42PinV1(t)
	got, err := expectedPinV1(p)
	if err != nil {
		t.Fatal(err)
	}
	if got != want {
		t.Fatalf("seed42 pin mismatch\ngot=%x\nwant=%x", pinBytesV1(got), pinBytesV1(want))
	}
	clientWire, relayWire := wirePinV1(want), wirePinV1(want)
	raw, _ := json.Marshal(catalogWireV1{AuthorizationCatalogVersionV1, AuthorizationCatalogScopeExplicitV1, []entryWireV1{{42, clientWire, relayWire}}})
	catalog, err := ParseAuthorizationCatalogV1(raw)
	if err != nil {
		t.Fatal(err)
	}
	if reflect.TypeOf(catalog.client) == reflect.TypeOf(catalog.relay) {
		t.Fatal("role catalog types collapsed")
	}
	if &catalog.client.entries[0] == &catalog.relay.entries[0] {
		t.Fatal("role provenance aliased")
	}
}

func TestStrictGenerateIndependentRoleAndOwnershipEvidence(t *testing.T) {
	p, err := compiler.Generate(42)
	if err != nil {
		t.Fatal(err)
	}
	pin := independentSeed42PinV1(t)
	makeCatalog := func(client, relay AuthorizationPinV1) AuthorizationCatalogV1 {
		raw, _ := json.Marshal(catalogWireV1{AuthorizationCatalogVersionV1, AuthorizationCatalogScopeExplicitV1, []entryWireV1{{42, wirePinV1(client), wirePinV1(relay)}}})
		c, e := ParseAuthorizationCatalogV1(raw)
		if e != nil {
			t.Fatal(e)
		}
		return c
	}
	good := makeCatalog(pin, pin)
	out := filepath.Join(t.TempDir(), "independent-success")
	if _, err := GenerateStrict(p, out, Options{GeneratedAt: time.Unix(0, 0).UTC()}, good); err != nil {
		t.Fatal(err)
	}
	for _, role := range []string{"client", "relay"} {
		client, relay := pin, pin
		if role == "client" {
			client.ProfileHash[0] ^= 1
		} else {
			relay.ProfileHash[0] ^= 1
		}
		bad := makeCatalog(client, relay)
		badOut := filepath.Join(t.TempDir(), role)
		if _, err := GenerateStrict(p, badOut, Options{}, bad); !errors.Is(err, ErrAuthorizationMismatch) {
			t.Fatalf("%s err=%v", role, err)
		}
		if _, err := os.Stat(badOut); !os.IsNotExist(err) {
			t.Fatalf("%s wrote output", role)
		}
	}
	mutated := good
	mutated.client.entries[0].pin.ProfileHash[0] ^= 1
	mutOut := filepath.Join(t.TempDir(), "mutated")
	if _, err := GenerateStrict(p, mutOut, Options{}, mutated); !errors.Is(err, ErrAuthorizationCatalogInvalid) {
		t.Fatalf("mutation err=%v", err)
	}
	if _, err := os.Stat(mutOut); !os.IsNotExist(err) {
		t.Fatal("mutated catalog wrote output")
	}
}

func TestAuthorizationV1ArchitectureAndSelectorEvidence(t *testing.T) {
	_, file, _, _ := runtime.Caller(0)
	dir := filepath.Dir(file)
	auth, err := os.ReadFile(filepath.Join(dir, "authorization_v1.go"))
	if err != nil {
		t.Fatal(err)
	}
	text := string(auth)
	for _, forbidden := range []string{"internal/runtime", "runtime.Registry", "payload", "identity_key", "destination", "secret"} {
		if strings.Contains(text, forbidden) {
			t.Fatalf("authorization DTO contains forbidden %q", forbidden)
		}
	}
	gen, err := os.ReadFile(filepath.Join(dir, "generator.go"))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(gen), "int(seed) %") || strings.Contains(string(gen), "math.Abs") {
		t.Fatal("unsafe signed selector source")
	}
	for _, tc := range []struct {
		seed    int64
		n, want int
	}{{0, 3, 0}, {1, 3, 1}, {42, 3, 0}, {-1, 3, 0}, {math.MinInt64, 3, 2}, {math.MaxInt64, 3, 1}} {
		if got := signedSafeModeIndex(tc.seed, tc.n); got != tc.want {
			t.Fatalf("seed=%d got=%d want=%d", tc.seed, got, tc.want)
		}
	}
}

func independentPinBytesV1(p AuthorizationPinV1) []byte {
	var out bytes.Buffer
	for _, h := range [][32]byte{p.ProfileHash, p.EffectivePolicyHash, p.FramingHash, p.StateMachineHash, p.SchedulerHash, p.PaddingHash, p.StreamHash, p.ProxyHash, p.CarrierContextHash} {
		out.Write(h[:])
	}
	for _, v := range []uint32{p.EffectiveReplayWindow, p.EffectiveMaxConcurrentStreams, p.EffectiveMaxFrameBytes, p.EffectiveMaxEnvelopeBytes} {
		var b [4]byte
		binary.BigEndian.PutUint32(b[:], v)
		out.Write(b[:])
	}
	return out.Bytes()
}
func independentLPV1(out *bytes.Buffer, v []byte) {
	var b [4]byte
	binary.BigEndian.PutUint32(b[:], uint32(len(v)))
	out.Write(b[:])
	out.Write(v)
}
func TestAuthorizationCatalogIndependentCanonicalSignedVector(t *testing.T) {
	seeds := []int64{math.MinInt64, math.MinInt64 + 1, math.MinInt64 + 2}
	entries := make([]entryWireV1, 0, len(seeds))
	for i, seed := range seeds {
		var p AuthorizationPinV1
		for field := 0; field < 9; field++ {
			value := sha256.Sum256([]byte{byte(i + 1), byte(field + 1)})
			switch field {
			case 0:
				p.ProfileHash = value
			case 1:
				p.EffectivePolicyHash = value
			case 2:
				p.FramingHash = value
			case 3:
				p.StateMachineHash = value
			case 4:
				p.SchedulerHash = value
			case 5:
				p.PaddingHash = value
			case 6:
				p.StreamHash = value
			case 7:
				p.ProxyHash = value
			case 8:
				p.CarrierContextHash = value
			}
		}
		p.EffectiveReplayWindow = 1
		p.EffectiveMaxConcurrentStreams = 2
		p.EffectiveMaxFrameBytes = 3
		p.EffectiveMaxEnvelopeBytes = 4
		entries = append(entries, entryWireV1{seed, wirePinV1(p), wirePinV1(p)})
	}
	raw, _ := json.Marshal(catalogWireV1{AuthorizationCatalogVersionV1, AuthorizationCatalogScopeExplicitV1, entries})
	c, err := ParseAuthorizationCatalogV1(raw)
	if err != nil {
		t.Fatal(err)
	}
	var independent bytes.Buffer
	independentLPV1(&independent, []byte("kurdistan/codegen/authorization-catalog/v1"))
	independentLPV1(&independent, []byte(AuthorizationCatalogVersionV1))
	independentLPV1(&independent, []byte(AuthorizationCatalogScopeExplicitV1))
	var count [4]byte
	binary.BigEndian.PutUint32(count[:], 3)
	independent.Write(count[:])
	for i, seed := range seeds {
		var b [8]byte
		binary.BigEndian.PutUint64(b[:], uint64(seed))
		independent.Write(b[:])
		pin, _ := parsePinV1(entries[i].Client)
		independentLPV1(&independent, []byte("client"))
		independentLPV1(&independent, independentPinBytesV1(pin))
		independentLPV1(&independent, []byte("relay"))
		independentLPV1(&independent, independentPinBytesV1(pin))
	}
	got, _ := c.canonical()
	if !bytes.Equal(got, independent.Bytes()) || c.digest != sha256.Sum256(independent.Bytes()) {
		t.Fatal("independent canonical vector mismatch")
	}
	if err := c.validate(); err != nil {
		t.Fatalf("catalog validation: %v", err)
	}
	if err := c.ValidateExactSeedRangeV1(AuthorizationCatalogScopeExplicitV1, math.MinInt64, 3); err != nil {
		t.Fatal(err)
	}
}

func TestAuthorizationCatalogExhaustiveSchemaAndBounds(t *testing.T) {
	p, _ := compiler.Generate(44)
	pin, _ := expectedPinV1(p)
	base := catalogWireV1{AuthorizationCatalogVersionV1, AuthorizationCatalogScopeExplicitV1, []entryWireV1{{p.Seed, wirePinV1(pin), wirePinV1(pin)}}}
	good, _ := json.Marshal(base)
	mutations := [][]byte{[]byte(`{}`), []byte(`{"version":"profile-authorization-catalog-v1","scope":"explicit_v1","entries":[],"extra":1}`), []byte(strings.Replace(string(good), `"seed":44`, `"seed":44,"seed":45`, 1)), []byte(strings.Replace(string(good), `"client":`, `"unknown":1,"client":`, 1)), []byte(strings.Replace(string(good), `"profile_hash":`, `"profile_hash":"","profile_hash_2":`, 1))}
	for i, raw := range mutations {
		if _, err := ParseAuthorizationCatalogV1(raw); !errors.Is(err, ErrAuthorizationCatalogInvalid) {
			t.Fatalf("mutation %d err=%v", i, err)
		}
	}
	exact := append(good, bytes.Repeat([]byte(" "), (1<<20)-len(good))...)
	if _, err := ParseAuthorizationCatalogV1(exact); err != nil {
		t.Fatal(err)
	}
	if _, err := ParseAuthorizationCatalogV1(append(exact, ' ')); !errors.Is(err, ErrAuthorizationCatalogInvalid) {
		t.Fatal(err)
	}
	entries := make([]entryWireV1, 513)
	for i := range entries {
		q := pin
		q.ProfileHash = sha256.Sum256([]byte{byte(i), byte(i >> 8), 1})
		entries[i] = entryWireV1{int64(i), wirePinV1(q), wirePinV1(q)}
	}
	withinEntryLimit, _ := json.Marshal(catalogWireV1{AuthorizationCatalogVersionV1, AuthorizationCatalogScopeExplicitV1, entries[:512]})
	if len(withinEntryLimit) > 1<<20 {
		t.Fatalf("512-entry fixture unexpectedly exceeds byte limit: %d", len(withinEntryLimit))
	}
	if _, err := ParseAuthorizationCatalogV1(withinEntryLimit); err != nil {
		t.Fatalf("512 entries rejected: %v", err)
	}
	raw, _ := json.Marshal(catalogWireV1{AuthorizationCatalogVersionV1, AuthorizationCatalogScopeExplicitV1, entries})
	if _, err := ParseAuthorizationCatalogV1(raw); !errors.Is(err, ErrAuthorizationCatalogInvalid) {
		t.Fatal(err)
	}

	// A later relay cannot reuse an earlier client profile hash (or vice versa).
	second := pin
	second.ProfileHash = sha256.Sum256([]byte("second-profile"))
	crossRole := []entryWireV1{{0, wirePinV1(pin), wirePinV1(pin)}, {1, wirePinV1(second), wirePinV1(pin)}}
	raw, _ = json.Marshal(catalogWireV1{AuthorizationCatalogVersionV1, AuthorizationCatalogScopeExplicitV1, crossRole})
	if _, err := ParseAuthorizationCatalogV1(raw); !errors.Is(err, ErrAuthorizationCatalogInvalid) {
		t.Fatalf("cross-role profile reuse err=%v", err)
	}
}

func TestAuthorizationCatalogRangeQueryMatrix(t *testing.T) {
	// Reuse the signed independent fixture and prove every range failure stays catalog-invalid.
	p, _ := compiler.Generate(45)
	c := catalogFixtureV1(t, p)
	for _, tc := range []struct {
		scope string
		start int64
		count int
	}{{"bad", p.Seed, 1}, {AuthorizationCatalogScopeExplicitV1, p.Seed, 0}, {AuthorizationCatalogScopeExplicitV1, p.Seed, 2}, {AuthorizationCatalogScopeExplicitV1, math.MaxInt64, 2}} {
		if err := c.ValidateExactSeedRangeV1(tc.scope, tc.start, tc.count); !errors.Is(err, ErrAuthorizationCatalogInvalid) || err.Error() != ErrAuthorizationCatalogInvalid.Error() {
			t.Fatalf("case=%+v err=%v", tc, err)
		}
	}
}

func TestStrictGenerateAllPinMismatchAndPreOutput(t *testing.T) {
	p, _ := compiler.Generate(46)
	want, _ := expectedPinV1(p)
	mutators := []func(*AuthorizationPinV1){func(v *AuthorizationPinV1) { v.ProfileHash[0] ^= 1 }, func(v *AuthorizationPinV1) { v.EffectivePolicyHash[0] ^= 1 }, func(v *AuthorizationPinV1) { v.FramingHash[0] ^= 1 }, func(v *AuthorizationPinV1) { v.StateMachineHash[0] ^= 1 }, func(v *AuthorizationPinV1) { v.SchedulerHash[0] ^= 1 }, func(v *AuthorizationPinV1) { v.PaddingHash[0] ^= 1 }, func(v *AuthorizationPinV1) { v.StreamHash[0] ^= 1 }, func(v *AuthorizationPinV1) { v.ProxyHash[0] ^= 1 }, func(v *AuthorizationPinV1) { v.CarrierContextHash[0] ^= 1 }, func(v *AuthorizationPinV1) { v.EffectiveReplayWindow++ }, func(v *AuthorizationPinV1) { v.EffectiveMaxConcurrentStreams++ }, func(v *AuthorizationPinV1) { v.EffectiveMaxFrameBytes++ }, func(v *AuthorizationPinV1) { v.EffectiveMaxEnvelopeBytes++ }}
	for i, mutate := range mutators {
		bad := want
		mutate(&bad)
		raw, _ := json.Marshal(catalogWireV1{AuthorizationCatalogVersionV1, AuthorizationCatalogScopeExplicitV1, []entryWireV1{{p.Seed, wirePinV1(bad), wirePinV1(bad)}}})
		c, err := ParseAuthorizationCatalogV1(raw)
		if err != nil {
			t.Fatal(err)
		}
		out := filepath.Join(t.TempDir(), "must-not-exist")
		if _, err := GenerateStrict(p, out, Options{}, c); !errors.Is(err, ErrAuthorizationMismatch) || err.Error() != ErrAuthorizationMismatch.Error() {
			t.Fatalf("pin %d err=%v", i, err)
		}
		if _, err := os.Stat(out); !os.IsNotExist(err) {
			t.Fatalf("pin %d mutated output", i)
		}
	}
}

func catalogRawV1(t *testing.T, scope string, entries []entryWireV1) []byte {
	t.Helper()
	raw, err := json.Marshal(catalogWireV1{AuthorizationCatalogVersionV1, scope, entries})
	if err != nil {
		t.Fatal(err)
	}
	return raw
}

func independentEntryV1(t *testing.T, seed int64) entryWireV1 {
	t.Helper()
	p, err := compiler.Generate(seed)
	if err != nil {
		t.Fatal(err)
	}
	pin, err := expectedPinV1(p)
	if err != nil {
		t.Fatal(err)
	}
	return entryWireV1{seed, wirePinV1(pin), wirePinV1(pin)}
}

func TestAuthorizationCatalogParserRequirementMatrix(t *testing.T) {
	base := independentEntryV1(t, 47)
	good := catalogRawV1(t, AuthorizationCatalogScopeExplicitV1, []entryWireV1{base})
	assertInvalid := func(name string, raw []byte) {
		t.Helper()
		if _, err := ParseAuthorizationCatalogV1(raw); !errors.Is(err, ErrAuthorizationCatalogInvalid) || err.Error() != ErrAuthorizationCatalogInvalid.Error() {
			t.Fatalf("%s: %v", name, err)
		}
	}
	// Exact key sets at every level, role omission, input digest, and duplicate keys.
	for name, raw := range map[string][]byte{
		"top omission":   []byte(`{"version":"profile-authorization-catalog-v1","scope":"explicit_v1"}`),
		"input digest":   []byte(strings.Replace(string(good), `"entries":`, `"digest":"00","entries":`, 1)),
		"entry omission": []byte(strings.Replace(string(good), `,"relay":`+string(mustJSONV1(t, base.Relay)), ``, 1)),
		"pin omission":   []byte(strings.Replace(string(good), `,"effective_max_envelope_bytes":8192`, ``, 1)),
		"pin unknown":    []byte(strings.Replace(string(good), `"profile_hash":`, `"extra":1,"profile_hash":`, 1)),
		"duplicate pin":  []byte(strings.Replace(string(good), `"profile_hash":`, `"profile_hash":"00","profile_hash":`, 1)),
	} {
		assertInvalid(name, raw)
	}

	// Hash representation and per-pin uniqueness.
	var wire catalogWireV1
	if err := json.Unmarshal(good, &wire); err != nil {
		t.Fatal(err)
	}
	for name, mutate := range map[string]func(*pinWireV1){
		"upper":          func(p *pinWireV1) { p.ProfileHash = strings.ToUpper(p.ProfileHash) },
		"short":          func(p *pinWireV1) { p.ProfileHash = p.ProfileHash[:62] },
		"nonhex":         func(p *pinWireV1) { p.ProfileHash = strings.Repeat("z", 64) },
		"zero":           func(p *pinWireV1) { p.ProfileHash = strings.Repeat("0", 64) },
		"duplicate hash": func(p *pinWireV1) { p.FramingHash = p.ProfileHash },
		"zero tuple":     func(p *pinWireV1) { p.EffectiveReplayWindow = 0 },
	} {
		bad := wire
		bad.Entries = append([]entryWireV1(nil), wire.Entries...)
		mutate(&bad.Entries[0].Client)
		assertInvalid(name, mustJSONV1(t, bad))
	}

	// Seed/profile duplicates, noncanonical order, supported scopes, and signed extremes.
	first := independentEntryV1(t, 48)
	second := independentEntryV1(t, 49)
	assertInvalid("duplicate seed", catalogRawV1(t, AuthorizationCatalogScopeExplicitV1, []entryWireV1{first, first}))
	assertInvalid("noncanonical seed", catalogRawV1(t, AuthorizationCatalogScopeExplicitV1, []entryWireV1{second, first}))
	profileDuplicate := second
	profileDuplicate.Client.ProfileHash = first.Client.ProfileHash
	assertInvalid("duplicate profile", catalogRawV1(t, AuthorizationCatalogScopeExplicitV1, []entryWireV1{first, profileDuplicate}))
	assertInvalid("unknown scope", catalogRawV1(t, "unknown", []entryWireV1{first}))
	for _, scope := range []string{AuthorizationCatalogScopeDefaultAuditV1, AuthorizationCatalogScopeExplicitV1} {
		if _, err := ParseAuthorizationCatalogV1(catalogRawV1(t, scope, []entryWireV1{first})); err != nil {
			t.Fatalf("scope %s: %v", scope, err)
		}
	}
	if AuthorizationCatalogVersionV1 != "profile-authorization-catalog-v1" || AuthorizationCatalogScopeDefaultAuditV1 != "default_audit_v1" || AuthorizationCatalogScopeExplicitV1 != "explicit_v1" {
		t.Fatal("constant drift")
	}
}

func mustJSONV1(t *testing.T, v any) []byte {
	t.Helper()
	b, err := json.Marshal(v)
	if err != nil {
		t.Fatal(err)
	}
	return b
}

func TestAuthorizationCatalogCanonicalPermutationAndCloneIsolation(t *testing.T) {
	entry := independentEntryV1(t, 50)
	// Give each role distinct provenance while retaining valid, independently encoded pins.
	relayHash := sha256.Sum256([]byte("independent-relay-profile-50"))
	entry.Relay.ProfileHash = hex.EncodeToString(relayHash[:])
	ordered := catalogRawV1(t, AuthorizationCatalogScopeExplicitV1, []entryWireV1{entry})
	permuted := []byte(`{"entries":` + string(mustJSONV1(t, []entryWireV1{entry})) + `,"scope":"explicit_v1","version":"profile-authorization-catalog-v1"}`)
	a, err := ParseAuthorizationCatalogV1(ordered)
	if err != nil {
		t.Fatal(err)
	}
	b, err := ParseAuthorizationCatalogV1(permuted)
	if err != nil {
		t.Fatal(err)
	}
	ac, _ := a.canonical()
	bc, _ := b.canonical()
	if !bytes.Equal(ac, bc) || a.digest != b.digest {
		t.Fatal("member permutation changed canonical catalog")
	}
	if a.client.entries[0].pin == a.relay.entries[0].pin {
		t.Fatal("asymmetric role pins collapsed")
	}
	// Parsed state owns its data: changing caller bytes and a copied role slice cannot silently validate.
	before := a.digest
	for i := range ordered {
		ordered[i] ^= 0xff
	}
	if a.digest != before || a.validate() != nil {
		t.Fatal("caller mutation altered parsed catalog")
	}
	copyCatalog := a
	copyCatalog.client.entries = append([]authorizationEntryV1(nil), a.client.entries...)
	copyCatalog.relay.entries = append([]authorizationEntryV1(nil), a.relay.entries...)
	copyCatalog.client.entries[0].pin.ProfileHash[0] ^= 1
	if a.validate() != nil || copyCatalog.validate() == nil {
		t.Fatal("deep-clone isolation not enforced")
	}
}

func TestAuthorizationCatalogIndependentAsymmetricCanonicalOracle(t *testing.T) {
	entry := independentEntryV1(t, 50)
	client, err := parsePinV1(entry.Client)
	if err != nil {
		t.Fatal(err)
	}
	relay := client
	for i := 0; i < 9; i++ {
		h := sha256.Sum256([]byte(fmt.Sprintf("asymmetric-relay-%d", i)))
		switch i {
		case 0:
			relay.ProfileHash = h
		case 1:
			relay.EffectivePolicyHash = h
		case 2:
			relay.FramingHash = h
		case 3:
			relay.StateMachineHash = h
		case 4:
			relay.SchedulerHash = h
		case 5:
			relay.PaddingHash = h
		case 6:
			relay.StreamHash = h
		case 7:
			relay.ProxyHash = h
		case 8:
			relay.CarrierContextHash = h
		}
	}
	relay.EffectiveReplayWindow++
	relay.EffectiveMaxConcurrentStreams++
	relay.EffectiveMaxFrameBytes++
	relay.EffectiveMaxEnvelopeBytes++
	entry.Relay = wirePinV1(relay)
	c, err := ParseAuthorizationCatalogV1(catalogRawV1(t, AuthorizationCatalogScopeExplicitV1, []entryWireV1{entry}))
	if err != nil {
		t.Fatal(err)
	}
	var want bytes.Buffer
	independentLPV1(&want, []byte("kurdistan/codegen/authorization-catalog/v1"))
	independentLPV1(&want, []byte(AuthorizationCatalogVersionV1))
	independentLPV1(&want, []byte(AuthorizationCatalogScopeExplicitV1))
	var count [4]byte
	binary.BigEndian.PutUint32(count[:], 1)
	want.Write(count[:])
	var seed [8]byte
	binary.BigEndian.PutUint64(seed[:], uint64(50))
	want.Write(seed[:])
	independentLPV1(&want, []byte("client"))
	independentLPV1(&want, independentPinBytesV1(client))
	independentLPV1(&want, []byte("relay"))
	independentLPV1(&want, independentPinBytesV1(relay))
	got, err := c.canonical()
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, want.Bytes()) || c.digest != sha256.Sum256(want.Bytes()) {
		t.Fatal("asymmetric independent canonical oracle mismatch")
	}
}

func TestAuthorizationCatalogExactRangeMatrix(t *testing.T) {
	entries := []entryWireV1{independentEntryV1(t, 51), independentEntryV1(t, 52), independentEntryV1(t, 53)}
	c, err := ParseAuthorizationCatalogV1(catalogRawV1(t, AuthorizationCatalogScopeExplicitV1, entries))
	if err != nil {
		t.Fatal(err)
	}
	if err := c.ValidateExactSeedRangeV1(AuthorizationCatalogScopeExplicitV1, 51, 3); err != nil {
		t.Fatal(err)
	}
	for _, tc := range []struct {
		start int64
		count int
	}{{50, 3}, {51, 2}, {51, 4}, {math.MaxInt64, 2}} {
		if err := c.ValidateExactSeedRangeV1(AuthorizationCatalogScopeExplicitV1, tc.start, tc.count); !errors.Is(err, ErrAuthorizationCatalogInvalid) {
			t.Fatalf("%+v: %v", tc, err)
		}
	}
	// Signed minimum is accepted by the query without negation or overflow.
	minEntries := make([]entryWireV1, 3)
	for i := range minEntries {
		minEntries[i] = entries[i]
		minEntries[i].Seed = math.MinInt64 + int64(i)
	}
	minCatalog, err := ParseAuthorizationCatalogV1(catalogRawV1(t, AuthorizationCatalogScopeExplicitV1, minEntries))
	if err != nil {
		t.Fatal(err)
	}
	if err := minCatalog.ValidateExactSeedRangeV1(AuthorizationCatalogScopeExplicitV1, math.MinInt64, 3); err != nil {
		t.Fatal(err)
	}
}

func TestStrictGenerateSignedBoundaryMultiSeedAndPreOutput(t *testing.T) {
	makeCatalog := func(profiles ...*ir.Profile) AuthorizationCatalogV1 {
		entries := make([]entryWireV1, len(profiles))
		for i, p := range profiles {
			pin, err := expectedPinV1(p)
			if err != nil {
				t.Fatal(err)
			}
			entries[i] = entryWireV1{p.Seed, wirePinV1(pin), wirePinV1(pin)}
		}
		sort.Slice(entries, func(i, j int) bool { return entries[i].Seed < entries[j].Seed })
		c, err := ParseAuthorizationCatalogV1(catalogRawV1(t, AuthorizationCatalogScopeExplicitV1, entries))
		if err != nil {
			t.Fatal(err)
		}
		return c
	}
	base, err := compiler.Generate(42)
	if err != nil {
		t.Fatal(err)
	}
	profiles := make([]*ir.Profile, 0, 4)
	for _, seed := range []int64{math.MinInt64, -1, 0, 1} {
		p := *base
		p.Seed = seed
		key := sha256.Sum256([]byte(fmt.Sprintf("test-only-key:%s:%d", p.ID, seed)))
		p.Auth.TestKeyHex = hex.EncodeToString(key[:])
		p.GenerationHash = ""
		hash, err := ir.CanonicalHash(&p)
		if err != nil {
			t.Fatal(err)
		}
		p.GenerationHash = hash
		profiles = append(profiles, &p)
	}
	multi := makeCatalog(profiles...)
	for _, p := range profiles {
		if _, err := GenerateStrict(p, filepath.Join(t.TempDir(), "signed"), Options{}, multi); err != nil {
			t.Fatalf("seed %d: %v", p.Seed, err)
		}
	}
	missing, _ := compiler.Generate(2)
	missingOut := filepath.Join(t.TempDir(), "missing")
	if _, err := GenerateStrict(missing, missingOut, Options{}, multi); !errors.Is(err, ErrAuthorizationMismatch) {
		t.Fatal(err)
	}
	if _, err := os.Stat(missingOut); !os.IsNotExist(err) {
		t.Fatal("missing seed wrote output")
	}
	for _, seed := range []int64{math.MaxInt64 - 6, math.MaxInt64} {
		p := *profiles[1]
		p.Seed = seed
		out := filepath.Join(t.TempDir(), "overflow")
		if _, err := GenerateStrict(&p, out, Options{}, AuthorizationCatalogV1{}); !errors.Is(err, ErrStrictSeedRange) || err.Error() != ErrStrictSeedRange.Error() {
			t.Fatalf("seed %d: %v", seed, err)
		}
		if _, err := os.Stat(out); !os.IsNotExist(err) {
			t.Fatalf("seed %d wrote output", seed)
		}
	}
	// The inclusive upper boundary passes seed-range validation and reaches catalog selection.
	boundary := *profiles[2]
	boundary.Seed = math.MaxInt64 - 7
	key := sha256.Sum256([]byte(fmt.Sprintf("test-only-key:%s:%d", boundary.ID, boundary.Seed)))
	boundary.Auth.TestKeyHex = hex.EncodeToString(key[:])
	boundary.GenerationHash = ""
	hash, err := ir.CanonicalHash(&boundary)
	if err != nil {
		t.Fatal(err)
	}
	boundary.GenerationHash = hash
	boundaryCatalog := makeCatalog(&boundary)
	if _, err := GenerateStrict(&boundary, filepath.Join(t.TempDir(), "boundary"), Options{}, boundaryCatalog); err != nil {
		t.Fatalf("boundary: %v", err)
	}
}

func TestAuthorizationV1SelectorsExactOutputs(t *testing.T) {
	for _, tc := range []struct {
		seed                         int64
		assignment, churn, migration string
	}{
		{0, "one_profile_per_relay", "fixed_interval_churn", "graceful_profile_migration"},
		{1, "profile_rotation", "risk_threshold_churn", "relay_to_relay_migration"},
		{42, "family_rotation", "observation_count_churn", "risk_triggered_migration"},
		{-1, "one_profile_per_relay", "fixed_interval_churn", "session_boundary_migration"},
		{math.MinInt64, "wire_policy_rotation", "profile_reuse_churn", "graceful_profile_migration"},
	} {
		if relayFleetAssignmentMode(tc.seed) != tc.assignment || relayFleetChurnMode(tc.seed) != tc.churn || relayFleetMigrationMode(tc.seed) != tc.migration {
			t.Fatalf("selector seed %d", tc.seed)
		}
	}
}

func TestStrictGenerateAuthorizationNeverEmitted(t *testing.T) {
	p, _ := compiler.Generate(42)
	pin := independentSeed42PinV1(t)
	c, err := ParseAuthorizationCatalogV1(catalogRawV1(t, AuthorizationCatalogScopeExplicitV1, []entryWireV1{{42, wirePinV1(pin), wirePinV1(pin)}}))
	if err != nil {
		t.Fatal(err)
	}
	out := filepath.Join(t.TempDir(), "generated")
	if _, err := GenerateStrict(p, out, Options{}, c); err != nil {
		t.Fatal(err)
	}
	forbiddenValues := []string{"AuthorizationCatalogV1", "AuthorizationPinV1", "authorizationEntryV1", "runtime.Registry", `"effective_policy_hash"`, `"carrier_context_hash"`, `"effective_replay_window"`, `"authorization_secret"`, `"authorization_payload"`, `"authorization_identity_key"`, `"authorization_destination"`, `"authorization_runtime_token"`}
	err = filepath.Walk(out, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return err
		}
		b, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		text := string(b)
		for _, forbidden := range forbiddenValues {
			if strings.Contains(text, forbidden) {
				t.Fatalf("%s emitted %q", path, forbidden)
			}
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	canonical, err := c.canonical()
	if err != nil {
		t.Fatal(err)
	}
	for _, forbidden := range []string{"secret", "payload", "identity_key", "destination", "runtime_token"} {
		if bytes.Contains(canonical, []byte(forbidden)) {
			t.Fatalf("canonical authorization contains forbidden %q", forbidden)
		}
	}
}

func TestAuthorizationCatalogMaxInt64AndTupleMalformedMatrix(t *testing.T) {
	entry := independentEntryV1(t, 54)
	entry.Seed = math.MaxInt64
	good := catalogRawV1(t, AuthorizationCatalogScopeExplicitV1, []entryWireV1{entry})
	if _, err := ParseAuthorizationCatalogV1(good); err != nil {
		t.Fatalf("MaxInt64 parse: %v", err)
	}
	fields := []string{"effective_replay_window", "effective_max_concurrent_streams", "effective_max_frame_bytes", "effective_max_envelope_bytes"}
	for _, field := range fields {
		needle := fmt.Sprintf(`"%s":`, field)
		start := strings.Index(string(good), needle)
		if start < 0 {
			t.Fatal(field)
		}
		start += len(needle)
		end := start
		for end < len(good) && good[end] >= '0' && good[end] <= '9' {
			end++
		}
		for _, malformed := range []string{"-1", "1.5", `"1"`, "4294967296"} {
			raw := append([]byte(nil), good...)
			raw = append(append(raw[:start], []byte(malformed)...), raw[end:]...)
			if _, err := ParseAuthorizationCatalogV1(raw); !errors.Is(err, ErrAuthorizationCatalogInvalid) {
				t.Fatalf("%s=%s: %v", field, malformed, err)
			}
		}
	}
	// Every nonzero but wrong tuple member parses, then fails strict recomputation pre-output.
	p, _ := compiler.Generate(54)
	want, _ := expectedPinV1(p)
	mutators := []func(*AuthorizationPinV1){
		func(v *AuthorizationPinV1) { v.EffectiveReplayWindow++ },
		func(v *AuthorizationPinV1) { v.EffectiveMaxConcurrentStreams++ },
		func(v *AuthorizationPinV1) { v.EffectiveMaxFrameBytes++ },
		func(v *AuthorizationPinV1) { v.EffectiveMaxEnvelopeBytes++ },
	}
	for i, mutate := range mutators {
		client := want
		mutate(&client)
		c, err := ParseAuthorizationCatalogV1(catalogRawV1(t, AuthorizationCatalogScopeExplicitV1, []entryWireV1{{54, wirePinV1(client), wirePinV1(want)}}))
		if err != nil {
			t.Fatal(err)
		}
		out := filepath.Join(t.TempDir(), fmt.Sprintf("tuple-%d", i))
		if _, err := GenerateStrict(p, out, Options{}, c); !errors.Is(err, ErrAuthorizationMismatch) {
			t.Fatalf("tuple %d: %v", i, err)
		}
		if _, err := os.Stat(out); !os.IsNotExist(err) {
			t.Fatalf("tuple %d wrote output", i)
		}
	}
}

func TestAuthorizationV1SixPathSHA256Evidence(t *testing.T) {
	_, file, _, _ := runtime.Caller(0)
	root := filepath.Clean(filepath.Join(filepath.Dir(file), "..", ".."))
	verifyCommittedEvidenceSetV1(t, root, "WO-040", []committedEvidenceExpectationV1{
		{"internal/codegen/authorization_v1.go", "ABSENT"},
		{"internal/codegen/authorization_v1_test.go", "ABSENT"},
		{"internal/codegen/generator.go", "06873bd0001f41d358cc21a9e2920ef1fc2c67b3e561141171ebed46f8da6142"},
		{"internal/codegen/generator_test.go", "0dcbb2a95f14de69a198013bc7c64597716cf00f4f3b284f950e233571e0acbe"},
		{"internal/codegen/manifest.go", "8a44ade86b14c5aab5d2f67239cdfc76bd8b4ef90fbc40ac75de837f579c2f98"},
		{"internal/runtime/policy_enforcement_test.go", "ABSENT"},
	})
}

const committedEvidenceManifestPathV1 = "testdata/evidence/phase1-m0-committed-sha256.json"

type committedEvidenceManifestV1 struct {
	Schema                         string                                   `json:"schema"`
	HashAlgorithm                  string                                   `json:"hash_algorithm"`
	SourceCandidate                string                                   `json:"source_candidate"`
	Sets                           map[string][]committedEvidenceEntryV1    `json:"sets"`
	MaintenanceOverlays            map[string]committedMaintenanceOverlayV1 `json:"maintenance_overlays"`
	HelperOwnerOverlays            map[string]helperOwnerOverlayV1          `json:"helper_owner_overlays"`
	ValidatorOverlays              map[string]helperOwnerOverlayV1          `json:"validator_overlays"`
	ValidatorConsumerOverlays      map[string]helperOwnerOverlayV1          `json:"validator_consumer_overlays"`
	EvidenceConvergenceOverlays    map[string]helperOwnerOverlayV1          `json:"evidence_convergence_overlays"`
	Phase2CompleteOverlays         map[string]phase2CompleteOverlayV1       `json:"phase2_complete_overlays"`
	Phase3ContractOverlays         map[string]phase2CompleteOverlayV1       `json:"phase3_contract_overlays"`
	Phase4FallbackOverlays         map[string]phase2CompleteOverlayV1       `json:"phase4_fallback_overlays"`
	Phase5RelayDescriptorOverlays  map[string]phase2CompleteOverlayV1       `json:"phase5_relay_descriptor_overlays"`
	Phase6DiagnosticExportOverlays map[string]phase2CompleteOverlayV1       `json:"phase6_diagnostic_export_overlays"`
	Phase7AppRuntimeOverlays       map[string]phase2CompleteOverlayV1       `json:"phase7_app_runtime_overlays"`
}

type committedMaintenanceOverlayV1 struct {
	Version       string                      `json:"version"`
	SelfPath      string                      `json:"self_path"`
	SelfPreSHA256 string                      `json:"self_pre_sha256"`
	Paths         []string                    `json:"paths"`
	Entries       []helperOwnerOverlayEntryV1 `json:"entries"`
}

type helperOwnerOverlayV1 struct {
	Version                string                      `json:"version"`
	PredecessorManifestSHA string                      `json:"predecessor_manifest_sha256"`
	Entries                []helperOwnerOverlayEntryV1 `json:"entries"`
}
type helperOwnerOverlayEntryV1 struct {
	Path       string `json:"path"`
	PreSHA256  string `json:"pre_sha256"`
	PostSHA256 string `json:"post_sha256"`
}

type phase2CompleteOverlayV1 struct {
	Version                   string                         `json:"version"`
	PredecessorManifestSHA256 string                         `json:"predecessor_manifest_sha256"`
	Paths                     []string                       `json:"paths"`
	Entries                   []phase2CompleteOverlayEntryV1 `json:"entries"`
}

type phase2CompleteOverlayEntryV1 struct {
	Path        string `json:"path"`
	PreEvidence string `json:"pre_evidence"`
	PostSHA256  string `json:"post_sha256"`
}

const helperOwnerOverlayNameV1 = "m2-governance-foundation-helper-owners-v1"
const helperOwnerOverlayNameV2 = "m2-governance-foundation-helper-owners-v2"
const maintenanceOverlayNameV1 = "m2-governance-foundation-v1"
const validatorOverlayNameV1 = "m2-governance-foundation-validators-v1"
const validatorConsumerOverlayNameV1 = "m2-governance-foundation-validator-consumer-v1"
const evidenceConvergenceOverlayNameV1 = "m2-governance-foundation-evidence-convergence-v1"
const phase2CompleteOverlayNameV1 = "m2-governance-foundation-phase2-complete-v1"
const phase2PredecessorManifestSHA256V1 = "c89a6be543ec35e68bef3cd6d5a91b685b1a05e523aca264faabc6d4933c398b"

var helperOwnerPathsV1 = []string{"internal/audit/codegen_test.go", "internal/codegen/authorization_v1_test.go", "cmd/kgen/main_test.go"}
var helperOwnerPreHashesV1 = []string{"0874db08bb14f2d94b94b88171f1d78cd87dd34122e6ca39e3eb4ec9942a00ec", "9f1941a9ef49c70aedddddf11890ea97df0563c2b921c75a3300aee713faf9ac", "a80d10983b1e5684faf64011ee482a3a8216f2ab2393fbe9cd7570cbf4d5524d"}
var helperOwnerPostHashesV1 = []string{"5e7fff88d4e75aadf0b2306c9d9574b76e13a62c585deeebda53ba6a191832d1", "96e6e30ccfe131cfa0384fc4463ac2f75a4e9d0630179233dc40157f7839f30b", "bad5ffb692075048785a98b0c048761f06003462f1a202660b60bddf4c9103e4"}
var maintenancePathsV1 = []string{"README.md", "ROADMAP.md", "docs/GOVERNANCE.md", "docs/safety.md", "internal/audit/security.go", "internal/audit/security_test.go", "internal/runtime/policy_enforcement_test.go", "internal/" + "testkit/importrules/importrules_test.go", committedEvidenceManifestPathV1}
var maintenancePreHashesV1 = []string{"68ebebb5c733c2c8aa31d9d67bed24489635c82e38a0451a9ca6e9e6e0adcb8b", "40e8f73ea355dd5de75faca8b50ebb9fc374ad6e041716d08390d648eca95e06", "867efaac1bb01cdfa62f954ead7deb895f827382c5075f969facb74a30fa3f57", "b9e571e290c46faf42d77eff7eec254b9d2870a4f26d7ddca8f649896fa55662", "18a050fdb8278db4ab71c61974d08db75e200a4e451067ab66ca669ade9543ea", "3ecb03c06bceae8ba073755a02d56a45fdfbb1899342958b1057214b304bf053", "eb04ddfd64ede4e3d1fab0ed53f008b31afcf18a2a3a157dcb21d296c77045d4", "1128d762990de6bac542df8afbbb08de06cc726c1117ecf55ec8feb69edfe167"}
var maintenancePostHashesV1 = []string{"2014b1d01767cd945f1a8196f90c327ceeadbf50da69eb5185cdd215d85f29d2", "77e6ded9aebca49b2d57138860c4b9131ae2e93683b6d59c858506862a47cc85", "3d12024c334399629bed5f9f4e41b21b3639aeab96448770e49609268010b3b6", "2fd18a43301b48f2f0cc43c542de044989173e0cae756bd417751ce0599454b8", "b5be3c78bf856be24b92751f21fe54c7cb4a197c9f68aa7bf10d1129e6ba5c17", "b7449bc1148e01edaadfffed21626f0acc45c1fd114d606bf9abe4275a5a56e3", "a799b17b7218f806217ca551bb8807d380d193206c7151dab96add53affe0136", "3a170c4752fea63a728d55abff9b0c8a7c91e25e0c98d14bdd4c401e3b56a178"}
var validatorPathsV1 = []string{"internal/audit/security.go", "internal/audit/security_test.go", "internal/runtime/policy_enforcement_test.go"}
var validatorPreHashesV1 = []string{"b5be3c78bf856be24b92751f21fe54c7cb4a197c9f68aa7bf10d1129e6ba5c17", "b7449bc1148e01edaadfffed21626f0acc45c1fd114d606bf9abe4275a5a56e3", "a799b17b7218f806217ca551bb8807d380d193206c7151dab96add53affe0136"}
var convergencePathsV1 = []string{"cmd/kgen/main_test.go", "internal/audit/codegen_test.go", "internal/audit/security.go", "internal/audit/security_test.go", "internal/codegen/authorization_v1_test.go", "internal/runtime/policy_enforcement_test.go", "internal/" + "testkit/importrules/importrules_test.go"}
var convergencePreHashesV1 = []string{"aa0d56ec1b1ebeeab11c90497d1f252295682bfb4b9d0c096dcd5b0047558ac0", "7707d4faf66e9d20edbb157a3ad59d71c81d8d3b7f869d7529ff312f9fce073d", "985d46009b1ed6c0faade46de2574b940954de92ad6db8de3ddac0e29ea4a3ae", "f6b623b865407412856cbfc1c3748524b47ccae39ad3d33e40bd8977c9dbeab3", "abf9e52b55971aefb21dace2226dfe4b29c4b5b8478504f30868934af8d6b935", "53f9635f8761701cd2a9ce2762b3004ff3a0143097cb7334930e7b6f086e33b9", "81ae4a98530acc4a643fd824a939aa658eba6f8f6c4857b7978c1ebeb6853c9f"}
var phase2CompletePathsV1 = []string{"README.md", "ROADMAP.md", "cmd/kgen/main_test.go", "docs/GOVERNANCE.md", "docs/KIP-0001-threat-model.md", "docs/KIP-0066-product-layer-scaffold.md", "docs/KIP-0068-product-governance-foundation.md", "docs/KIP-0069-product-contracts-v1.md", "docs/safety.md", "internal/audit/codegen_test.go", "internal/audit/security.go", "internal/audit/security_test.go", "internal/codegen/authorization_v1_test.go", "internal/runtime/policy_enforcement_test.go", "internal/" + "testkit/importrules/importrules_test.go", committedEvidenceManifestPathV1}

type committedEvidenceEntryV1 struct {
	Path        string `json:"path"`
	PreEvidence string `json:"pre_evidence"`
	PostSHA256  string `json:"post_sha256"`
}

type committedEvidenceExpectationV1 struct {
	Path        string
	PreEvidence string
}

func verifyCommittedEvidenceSetV1(t *testing.T, root, set string, want []committedEvidenceExpectationV1) {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(committedEvidenceManifestPathV1)))
	if err != nil {
		t.Fatal(err)
	}
	var manifest committedEvidenceManifestV1
	if err := json.Unmarshal(raw, &manifest); err != nil {
		t.Fatal(err)
	}
	if manifest.Schema != "kurdistan.phase1-m0.committed-sha256.v1" || manifest.HashAlgorithm != "sha256" || manifest.SourceCandidate != "cad48bb4be28a09a6293944f78724d7026de4c12" {
		t.Fatalf("invalid committed evidence manifest identity: %+v", manifest)
	}
	historicalHashes, err := validateEvidenceOverlaysV1(root, manifest)
	if err != nil {
		t.Fatal(err)
	}
	requiredSets := map[string]bool{"WO-040": true, "WO-041": true, "WO-042": true, "WO-043": true, "WO-044": true}
	if len(manifest.Sets) != len(requiredSets) {
		t.Fatalf("committed evidence sets=%v", manifest.Sets)
	}
	for name := range manifest.Sets {
		if !requiredSets[name] {
			t.Fatalf("unexpected committed evidence set %q", name)
		}
	}
	entries, ok := manifest.Sets[set]
	if !ok || len(entries) != len(want) {
		t.Fatalf("%s evidence entries=%v want %d", set, entries, len(want))
	}
	for i, expected := range want {
		entry := entries[i]
		if entry.Path != expected.Path || entry.PreEvidence != expected.PreEvidence {
			t.Fatalf("%s evidence[%d]=%+v want path=%s pre=%s", set, i, entry, expected.Path, expected.PreEvidence)
		}
		if entry.Path == committedEvidenceManifestPathV1 || filepath.IsAbs(entry.Path) || filepath.ToSlash(filepath.Clean(entry.Path)) != entry.Path {
			t.Fatalf("%s invalid evidence path %q", set, entry.Path)
		}
		postBytes, err := hex.DecodeString(entry.PostSHA256)
		if err != nil || len(postBytes) != sha256.Size || entry.PostSHA256 != strings.ToLower(entry.PostSHA256) || entry.PostSHA256 == strings.Repeat("0", 64) {
			t.Fatalf("%s invalid post SHA-256 for %s", set, entry.Path)
		}
		if entry.PreEvidence != "ABSENT" && entry.PreEvidence != "UNRECORDED" {
			preBytes, err := hex.DecodeString(entry.PreEvidence)
			if err != nil || len(preBytes) != sha256.Size || entry.PreEvidence != strings.ToLower(entry.PreEvidence) || entry.PreEvidence == entry.PostSHA256 {
				t.Fatalf("%s invalid pre evidence for %s", set, entry.Path)
			}
		}
		current, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(entry.Path)))
		if err != nil {
			t.Fatal(err)
		}
		sum := sha256.Sum256(current)
		post := hex.EncodeToString(sum[:])
		if historical, ok := historicalHashes[entry.Path]; ok {
			post = historical
		}
		if post != entry.PostSHA256 {
			t.Fatalf("%s committed SHA-256 %s=%s want %s", set, entry.Path, post, entry.PostSHA256)
		}
		t.Logf("%s-SHA256 %s pre=%s post=%s", set, entry.Path, entry.PreEvidence, post)
	}
}

func validateEvidenceOverlaysV1(root string, manifest committedEvidenceManifestV1) (map[string]string, error) {
	currentAtM6, err := validatePhase7AppRuntimeOverlayV1(root, manifest.Phase7AppRuntimeOverlays)
	if err != nil {
		return nil, err
	}
	currentAtM5, err := validatePhase6DiagnosticExportOverlayV1(root, currentAtM6, manifest.Phase6DiagnosticExportOverlays)
	if err != nil {
		return nil, err
	}
	currentAtM4, err := validatePhase5RelayDescriptorOverlayV1(root, currentAtM5, manifest.Phase5RelayDescriptorOverlays)
	if err != nil {
		return nil, err
	}
	currentAtM3, err := validatePhase4FallbackOverlayV1(root, currentAtM4, manifest.Phase4FallbackOverlays)
	if err != nil {
		return nil, err
	}
	currentAtM2, err := validatePhase3ContractOverlayV1(root, currentAtM3, manifest.Phase3ContractOverlays)
	if err != nil {
		return nil, err
	}
	currentAtPre, err := validatePhase2CompleteOverlayV1(root, currentAtM2, manifest.Phase2CompleteOverlays)
	if err != nil {
		return nil, err
	}
	currentAtPre, err = validateConvergenceOverlayV1(currentAtPre, manifest.EvidenceConvergenceOverlays)
	if err != nil {
		return nil, err
	}
	validators, ok := manifest.ValidatorOverlays[validatorOverlayNameV1]
	if len(manifest.ValidatorOverlays) != 1 || !ok || validators.Version != validatorOverlayNameV1 || validators.PredecessorManifestSHA != "7924eff0ab8d66440bd370af1c6073ca9dc9beb320ac68acd82748b7f2d4f87b" || len(validators.Entries) != 3 {
		return nil, fmt.Errorf("invalid validator overlay identity/cardinality")
	}
	for i, entry := range validators.Entries {
		if entry.Path != validatorPathsV1[i] || entry.PreSHA256 != validatorPreHashesV1[i] || currentAtPre[entry.Path] != entry.PostSHA256 {
			return nil, fmt.Errorf("invalid validator chain entry %d", i)
		}
		currentAtPre[entry.Path] = entry.PreSHA256
	}
	consumer, ok := manifest.ValidatorConsumerOverlays[validatorConsumerOverlayNameV1]
	if len(manifest.ValidatorConsumerOverlays) != 1 || !ok || consumer.Version != validatorConsumerOverlayNameV1 || consumer.PredecessorManifestSHA != "7924eff0ab8d66440bd370af1c6073ca9dc9beb320ac68acd82748b7f2d4f87b" || len(consumer.Entries) != 1 {
		return nil, fmt.Errorf("invalid validator-consumer overlay identity/cardinality")
	}
	consumerEntry := consumer.Entries[0]
	if consumerEntry.Path != "internal/"+"testkit/importrules/importrules_test.go" || consumerEntry.PreSHA256 != "3a170c4752fea63a728d55abff9b0c8a7c91e25e0c98d14bdd4c401e3b56a178" || currentAtPre[consumerEntry.Path] != consumerEntry.PostSHA256 {
		return nil, fmt.Errorf("invalid validator-consumer chain")
	}
	currentAtPre[consumerEntry.Path] = consumerEntry.PreSHA256
	if len(manifest.MaintenanceOverlays) != 1 {
		return nil, fmt.Errorf("maintenance overlays=%d want 1", len(manifest.MaintenanceOverlays))
	}
	maintenance, ok := manifest.MaintenanceOverlays[maintenanceOverlayNameV1]
	if !ok || maintenance.Version != maintenanceOverlayNameV1 || maintenance.SelfPath != committedEvidenceManifestPathV1 || maintenance.SelfPreSHA256 != "4400e503524d1277329f893be0773dee202d5108265f62d22830e09fc8f8fa53" || len(maintenance.Paths) != len(maintenancePathsV1) || len(maintenance.Entries) != len(maintenancePreHashesV1) {
		return nil, fmt.Errorf("invalid maintenance overlay identity/cardinality")
	}
	historical := map[string]string{}
	for i, path := range maintenancePathsV1 {
		if maintenance.Paths[i] != path {
			return nil, fmt.Errorf("maintenance path[%d]=%q want %q", i, maintenance.Paths[i], path)
		}
	}
	for i, entry := range maintenance.Entries {
		if entry.Path != maintenancePathsV1[i] || entry.PreSHA256 != maintenancePreHashesV1[i] || entry.PostSHA256 != maintenancePostHashesV1[i] {
			return nil, fmt.Errorf("invalid maintenance entry %d", i)
		}
		actual := currentAtPre[entry.Path]
		if actual == "" {
			actual, err = fileSHA256V1(root, entry.Path)
		}
		if err != nil || actual != entry.PostSHA256 {
			return nil, fmt.Errorf("maintenance hash drift %s=%s want %s: %v", entry.Path, actual, entry.PostSHA256, err)
		}
		historical[entry.Path] = entry.PreSHA256
	}
	if len(manifest.HelperOwnerOverlays) != 2 {
		return nil, fmt.Errorf("helper-owner overlays=%d want 2", len(manifest.HelperOwnerOverlays))
	}
	v1, ok1 := manifest.HelperOwnerOverlays[helperOwnerOverlayNameV1]
	v2, ok2 := manifest.HelperOwnerOverlays[helperOwnerOverlayNameV2]
	if !ok1 || v1.Version != helperOwnerOverlayNameV1 || v1.PredecessorManifestSHA != "b2a95c93332afbc13c73a4bb08e92067db97e93e843cb55e1f191b9c398e3c7b" || len(v1.Entries) != 3 {
		return nil, fmt.Errorf("invalid helper-owner v1 identity/cardinality")
	}
	if !ok2 || v2.Version != helperOwnerOverlayNameV2 || v2.PredecessorManifestSHA != "7258697b4806469afea99342d981e96b328114036668e874f7c0e5a597a94cc6" || len(v2.Entries) != 3 {
		return nil, fmt.Errorf("invalid helper-owner v2 identity/cardinality")
	}
	for i, path := range helperOwnerPathsV1 {
		oldEntry, newEntry := v1.Entries[i], v2.Entries[i]
		if oldEntry.Path != path || oldEntry.PreSHA256 != helperOwnerPreHashesV1[i] || oldEntry.PostSHA256 != helperOwnerPostHashesV1[i] {
			return nil, fmt.Errorf("invalid helper-owner v1 entry %d", i)
		}
		if newEntry.Path != path || newEntry.PreSHA256 != oldEntry.PostSHA256 || !validHelperOwnerSHA256V1(newEntry.PostSHA256) || newEntry.PostSHA256 == newEntry.PreSHA256 {
			return nil, fmt.Errorf("invalid helper-owner v2 entry %d", i)
		}
		actual := currentAtPre[path]
		if actual != newEntry.PostSHA256 {
			return nil, fmt.Errorf("helper-owner v2 hash drift %s=%s want %s: %v", path, actual, newEntry.PostSHA256, err)
		}
		historical[path] = oldEntry.PreSHA256
	}
	return historical, nil
}

func validatePhase2CompleteOverlayV1(root string, currentAtPost map[string]string, overlays map[string]phase2CompleteOverlayV1) (map[string]string, error) {
	overlay, ok := overlays[phase2CompleteOverlayNameV1]
	if len(overlays) != 1 || !ok || overlay.Version != phase2CompleteOverlayNameV1 || overlay.PredecessorManifestSHA256 != phase2PredecessorManifestSHA256V1 || len(overlay.Paths) != len(phase2CompletePathsV1) || len(overlay.Entries) != len(phase2CompletePathsV1)-1 {
		return nil, fmt.Errorf("invalid phase2-complete overlay identity/cardinality")
	}
	for i, path := range phase2CompletePathsV1 {
		if overlay.Paths[i] != path {
			return nil, fmt.Errorf("phase2-complete path[%d]=%q want %q", i, overlay.Paths[i], path)
		}
	}
	pre := make(map[string]string, len(currentAtPost))
	for path, hash := range currentAtPost {
		pre[path] = hash
	}
	for i, entry := range overlay.Entries {
		if entry.Path != phase2CompletePathsV1[i] || entry.Path == committedEvidenceManifestPathV1 || !validHelperOwnerSHA256V1(entry.PostSHA256) || (entry.PreEvidence != "ABSENT" && entry.PreEvidence != "UNRECORDED" && !validHelperOwnerSHA256V1(entry.PreEvidence)) {
			return nil, fmt.Errorf("invalid phase2-complete entry %d", i)
		}
		actual, ok := currentAtPost[entry.Path]
		var err error
		if !ok {
			actual, err = fileSHA256V1(root, entry.Path)
		}
		if err != nil || actual != entry.PostSHA256 {
			return nil, fmt.Errorf("phase2-complete hash drift %s=%s want %s: %v", entry.Path, actual, entry.PostSHA256, err)
		}
		if entry.PreEvidence == "ABSENT" || entry.PreEvidence == "UNRECORDED" {
			delete(pre, entry.Path)
		} else {
			pre[entry.Path] = entry.PreEvidence
		}
	}
	return pre, nil
}

func validatePhase7AppRuntimeOverlayV1(root string, overlays map[string]phase2CompleteOverlayV1) (map[string]string, error) {
	const name = "m7-offline-app-runtime-contract-v1"
	wantPaths := []string{
		"ROADMAP.md", "docs/KIP-0066-product-layer-scaffold.md", "docs/KIP-0068-product-governance-foundation.md", "docs/KIP-0069-product-contracts-v1.md",
		"docs/KIP-0074-offline-app-runtime-contract.md", "internal/product/appruntime/appruntime.go", "internal/product/appruntime/appruntime_test.go",
		"testdata/consumer/m7-app-runtime-sdk/go.mod", "testdata/consumer/m7-app-runtime-sdk/app_runtime_sdk_test.go", "cmd/kgen/main_test.go",
		"internal/audit/codegen_test.go", "internal/audit/security.go", "internal/audit/security_test.go", "internal/codegen/authorization_v1_test.go",
		"internal/runtime/policy_enforcement_test.go", "internal/" + "testkit/importrules/importrules_test.go", committedEvidenceManifestPathV1,
	}
	overlay, ok := overlays[name]
	if len(overlays) != 1 || !ok || overlay.Version != name || overlay.PredecessorManifestSHA256 != "34f5d8d2048faf1de49c2ccd2ebb4a5c507ad3bf0b2d75b5db1e7e6d5c13a0a7" || len(overlay.Paths) != len(wantPaths) || len(overlay.Entries) != len(wantPaths)-1 {
		return nil, fmt.Errorf("invalid phase7 app runtime overlay identity/cardinality")
	}
	pre := map[string]string{}
	for i, path := range wantPaths {
		if overlay.Paths[i] != path {
			return nil, fmt.Errorf("invalid phase7 app runtime path %d", i)
		}
	}
	for i, entry := range overlay.Entries {
		if entry.Path != wantPaths[i] || !validHelperOwnerSHA256V1(entry.PostSHA256) {
			return nil, fmt.Errorf("invalid phase7 app runtime entry %d", i)
		}
		actual, err := fileSHA256V1(root, entry.Path)
		if err != nil || actual != entry.PostSHA256 {
			return nil, fmt.Errorf("phase7 app runtime hash drift %s=%s want %s: %v", entry.Path, actual, entry.PostSHA256, err)
		}
		if entry.PreEvidence != "ABSENT" && entry.PreEvidence != "UNRECORDED" {
			if !validHelperOwnerSHA256V1(entry.PreEvidence) {
				return nil, fmt.Errorf("invalid phase7 app runtime pre evidence %s", entry.Path)
			}
			pre[entry.Path] = entry.PreEvidence
		}
	}
	return pre, nil
}

func validatePhase6DiagnosticExportOverlayV1(root string, currentAtPost map[string]string, overlays map[string]phase2CompleteOverlayV1) (map[string]string, error) {
	const name = "m6-offline-diagnostic-export-contract-v1"
	wantPaths := []string{
		"ROADMAP.md", "docs/KIP-0066-product-layer-scaffold.md", "docs/KIP-0068-product-governance-foundation.md", "docs/KIP-0069-product-contracts-v1.md",
		"docs/KIP-0073-offline-diagnostic-export-contract.md", "internal/product/diagnosticexport/diagnosticexport.go", "internal/product/diagnosticexport/diagnosticexport_test.go",
		"testdata/consumer/m6-diagnostic-export-sdk/go.mod", "testdata/consumer/m6-diagnostic-export-sdk/diagnostic_export_sdk_test.go", "cmd/kgen/main_test.go",
		"internal/audit/codegen_test.go", "internal/audit/security.go", "internal/audit/security_test.go", "internal/codegen/authorization_v1_test.go",
		"internal/runtime/policy_enforcement_test.go", "internal/" + "testkit/importrules/importrules_test.go", committedEvidenceManifestPathV1,
	}
	overlay, ok := overlays[name]
	if len(overlays) != 1 || !ok || overlay.Version != name || overlay.PredecessorManifestSHA256 != "77fcaaa94436a401f071fbfbade94baeb0cd770574c7309ae5c427a76c030977" || len(overlay.Paths) != len(wantPaths) || len(overlay.Entries) != len(wantPaths)-1 {
		return nil, fmt.Errorf("invalid phase6 diagnostic export overlay identity/cardinality")
	}
	pre := map[string]string{}
	for i, path := range wantPaths {
		if overlay.Paths[i] != path {
			return nil, fmt.Errorf("invalid phase6 diagnostic export path %d", i)
		}
	}
	for i, entry := range overlay.Entries {
		if entry.Path != wantPaths[i] || !validHelperOwnerSHA256V1(entry.PostSHA256) {
			return nil, fmt.Errorf("invalid phase6 diagnostic export entry %d", i)
		}
		actual, present := currentAtPost[entry.Path]
		var err error
		if !present {
			actual, err = fileSHA256V1(root, entry.Path)
		}
		if err != nil || actual != entry.PostSHA256 {
			return nil, fmt.Errorf("phase6 diagnostic export hash drift %s=%s want %s: %v", entry.Path, actual, entry.PostSHA256, err)
		}
		if entry.PreEvidence != "ABSENT" && entry.PreEvidence != "UNRECORDED" {
			if !validHelperOwnerSHA256V1(entry.PreEvidence) {
				return nil, fmt.Errorf("invalid phase6 diagnostic export pre evidence %s", entry.Path)
			}
			pre[entry.Path] = entry.PreEvidence
		}
	}
	return pre, nil
}

func validatePhase5RelayDescriptorOverlayV1(root string, currentAtPost map[string]string, overlays map[string]phase2CompleteOverlayV1) (map[string]string, error) {
	const name = "m5-offline-relay-descriptor-admission-v1"
	overlay, ok := overlays[name]
	if len(overlays) != 1 || !ok || overlay.Version != name || overlay.PredecessorManifestSHA256 != "709e4a5a7412ee115fc71c2d825ebe9ac4f167439b4861a1649dd63fcf0c150f" || len(overlay.Paths) != 17 || len(overlay.Entries) != 16 || overlay.Paths[16] != committedEvidenceManifestPathV1 {
		return nil, fmt.Errorf("invalid phase5 relay descriptor overlay identity/cardinality")
	}
	pre := map[string]string{}
	for i, entry := range overlay.Entries {
		if overlay.Paths[i] != entry.Path || !validHelperOwnerSHA256V1(entry.PostSHA256) {
			return nil, fmt.Errorf("invalid phase5 relay descriptor entry %d", i)
		}
		actual, present := currentAtPost[entry.Path]
		var err error
		if !present {
			actual, err = fileSHA256V1(root, entry.Path)
		}
		if err != nil || actual != entry.PostSHA256 {
			return nil, fmt.Errorf("phase5 relay descriptor hash drift %s=%s want %s: %v", entry.Path, actual, entry.PostSHA256, err)
		}
		if entry.PreEvidence != "ABSENT" && entry.PreEvidence != "UNRECORDED" {
			if !validHelperOwnerSHA256V1(entry.PreEvidence) {
				return nil, fmt.Errorf("invalid phase5 relay descriptor pre evidence %s", entry.Path)
			}
			pre[entry.Path] = entry.PreEvidence
		}
	}
	return pre, nil
}

func validatePhase4FallbackOverlayV1(root string, currentAtPost map[string]string, overlays map[string]phase2CompleteOverlayV1) (map[string]string, error) {
	const name = "m4-permitted-fallback-contract-v1"
	overlay, ok := overlays[name]
	if len(overlays) != 1 || !ok || overlay.Version != name || overlay.PredecessorManifestSHA256 != "772ae344c99edb21a4d04fadd77f51978a6e81aa4d555ec30190cb64e7a7c2d9" || len(overlay.Paths) != 17 || len(overlay.Entries) != 16 || overlay.Paths[16] != committedEvidenceManifestPathV1 {
		return nil, fmt.Errorf("invalid phase4 fallback overlay identity/cardinality")
	}
	pre := make(map[string]string, len(currentAtPost))
	for path, hash := range currentAtPost {
		pre[path] = hash
	}
	for i, entry := range overlay.Entries {
		if overlay.Paths[i] != entry.Path || !validHelperOwnerSHA256V1(entry.PostSHA256) {
			return nil, fmt.Errorf("invalid phase4 fallback entry %d", i)
		}
		actual, present := currentAtPost[entry.Path]
		var err error
		if !present {
			actual, err = fileSHA256V1(root, entry.Path)
		}
		if err != nil || actual != entry.PostSHA256 {
			return nil, fmt.Errorf("phase4 fallback hash drift %s=%s want %s: %v", entry.Path, actual, entry.PostSHA256, err)
		}
		if entry.PreEvidence == "ABSENT" || entry.PreEvidence == "UNRECORDED" {
			delete(pre, entry.Path)
		} else {
			if !validHelperOwnerSHA256V1(entry.PreEvidence) {
				return nil, fmt.Errorf("invalid phase4 pre evidence %s", entry.Path)
			}
			pre[entry.Path] = entry.PreEvidence
		}
	}
	return pre, nil
}

func validatePhase3ContractOverlayV1(root string, currentAtPost map[string]string, overlays map[string]phase2CompleteOverlayV1) (map[string]string, error) {
	const name = "m3-profile-lifecycle-contract-v1"
	overlay, ok := overlays[name]
	if len(overlays) != 1 || !ok || overlay.Version != name || overlay.PredecessorManifestSHA256 != "50fde6a39c0b5d987a16e370f2d10f0526759c03c0d5f73a316cffcc207e4d90" || len(overlay.Paths) != len(overlay.Entries)+1 || overlay.Paths[len(overlay.Paths)-1] != committedEvidenceManifestPathV1 {
		return nil, fmt.Errorf("invalid phase3 contract overlay identity/cardinality")
	}
	pre := make(map[string]string, len(currentAtPost))
	for path, hash := range currentAtPost {
		pre[path] = hash
	}
	for i, entry := range overlay.Entries {
		if overlay.Paths[i] != entry.Path || !validHelperOwnerSHA256V1(entry.PostSHA256) {
			return nil, fmt.Errorf("invalid phase3 contract entry %d", i)
		}
		actual, present := currentAtPost[entry.Path]
		var err error
		if !present {
			actual, err = fileSHA256V1(root, entry.Path)
		}
		if err != nil || actual != entry.PostSHA256 {
			return nil, fmt.Errorf("phase3 contract hash drift %s=%s want %s: %v", entry.Path, actual, entry.PostSHA256, err)
		}
		if entry.PreEvidence != "ABSENT" && entry.PreEvidence != "UNRECORDED" {
			if !validHelperOwnerSHA256V1(entry.PreEvidence) {
				return nil, fmt.Errorf("invalid phase3 pre evidence %s", entry.Path)
			}
			pre[entry.Path] = entry.PreEvidence
		} else {
			delete(pre, entry.Path)
		}
	}
	return pre, nil
}

func validateConvergenceOverlayV1(currentAtPost map[string]string, overlays map[string]helperOwnerOverlayV1) (map[string]string, error) {
	convergence, ok := overlays[evidenceConvergenceOverlayNameV1]
	if len(overlays) != 1 || !ok || convergence.Version != evidenceConvergenceOverlayNameV1 || convergence.PredecessorManifestSHA != "1502ae4db6d151839f554e6becde9e81994286cbff378945282739015492bf1e" || len(convergence.Entries) != 7 {
		return nil, fmt.Errorf("invalid convergence overlay identity/cardinality")
	}
	result := make(map[string]string, len(currentAtPost))
	for path, hash := range currentAtPost {
		result[path] = hash
	}
	for i, entry := range convergence.Entries {
		if entry.Path != convergencePathsV1[i] || entry.PreSHA256 != convergencePreHashesV1[i] || !validHelperOwnerSHA256V1(entry.PostSHA256) || entry.PostSHA256 == entry.PreSHA256 {
			return nil, fmt.Errorf("invalid convergence entry %d", i)
		}
		actual := currentAtPost[entry.Path]
		if actual != entry.PostSHA256 {
			return nil, fmt.Errorf("convergence hash drift %s=%s want %s", entry.Path, actual, entry.PostSHA256)
		}
		result[entry.Path] = entry.PreSHA256
	}
	return result, nil
}

func fileSHA256V1(root, path string) (string, error) {
	content, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(path)))
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("%x", sha256.Sum256(content)), nil
}

func validHelperOwnerSHA256V1(value string) bool {
	decoded, err := hex.DecodeString(value)
	return err == nil && len(decoded) == sha256.Size && value == strings.ToLower(value) && value != strings.Repeat("0", 64)
}

func TestM2HelperOwnerOverlayCompositionMutationsV2(t *testing.T) {
	root := filepath.Clean(filepath.Join("..", ".."))
	raw, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(committedEvidenceManifestPathV1)))
	if err != nil {
		t.Fatal(err)
	}
	var manifest committedEvidenceManifestV1
	if err := json.Unmarshal(raw, &manifest); err != nil {
		t.Fatal(err)
	}
	if _, err := validateEvidenceOverlaysV1(root, manifest); err != nil {
		t.Fatal(err)
	}
	base := manifest.HelperOwnerOverlays[helperOwnerOverlayNameV2]
	v1Raw, err := json.Marshal(manifest.HelperOwnerOverlays[helperOwnerOverlayNameV1])
	if err != nil {
		t.Fatal(err)
	}
	mutations := []func(*helperOwnerOverlayV1){func(v *helperOwnerOverlayV1) { v.Version = "wrong" }, func(v *helperOwnerOverlayV1) { v.PredecessorManifestSHA = strings.Repeat("1", 64) }, func(v *helperOwnerOverlayV1) { v.Entries = v.Entries[:2] }, func(v *helperOwnerOverlayV1) { v.Entries = append(v.Entries, helperOwnerOverlayEntryV1{}) }, func(v *helperOwnerOverlayV1) { v.Entries[0], v.Entries[1] = v.Entries[1], v.Entries[0] }, func(v *helperOwnerOverlayV1) { v.Entries[0].PreSHA256 = strings.Repeat("2", 64) }, func(v *helperOwnerOverlayV1) { v.Entries[0].PostSHA256 = strings.Repeat("3", 64) }}
	for i, mutate := range mutations {
		copyOverlay := base
		copyOverlay.Entries = append([]helperOwnerOverlayEntryV1(nil), base.Entries...)
		mutate(&copyOverlay)
		copyManifest := manifest
		copyManifest.HelperOwnerOverlays = map[string]helperOwnerOverlayV1{helperOwnerOverlayNameV1: manifest.HelperOwnerOverlays[helperOwnerOverlayNameV1], helperOwnerOverlayNameV2: copyOverlay}
		if _, err := validateEvidenceOverlaysV1(root, copyManifest); err == nil {
			t.Fatalf("helper-owner mutation %d accepted", i)
		}
		gotV1, _ := json.Marshal(copyManifest.HelperOwnerOverlays[helperOwnerOverlayNameV1])
		if string(gotV1) != string(v1Raw) {
			t.Fatalf("helper-owner v1 changed by mutation %d", i)
		}
	}
}
