// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright 2026 Saro
package org.kurdistanvpn.core.nativejni

import java.math.BigInteger
import java.nio.ByteBuffer
import java.security.Principal
import java.security.PublicKey
import java.security.cert.X509Certificate
import java.security.cert.CertificateFactory
import java.util.Base64
import java.util.Date
import javax.net.ssl.TrustManager
import javax.net.ssl.X509TrustManager
import org.junit.Assert.*
import org.junit.Test

class AndroidSystemTrustRootsV1Test {
    @Test fun legacyNegativeSerialRootDoesNotDisableOtherSystemAnchors() {
        val legacy = Certificate(2, serial = BigInteger.valueOf(-1))
        val supported = Certificate(3)
        val destination = ByteBuffer.allocateDirect(16)
        val written = intArrayOf(99)
        assertEquals(0, AndroidSystemTrustRootsV1(source(arrayOf(legacy, supported))).copyInto(destination, written) { false })
        assertEquals(10, written[0])
        val bytes = ByteArray(written[0]); destination.get(bytes)
        assertArrayEquals(byteArrayOf(1,0,1,0,0,0,3,0x30,0x30,0x30), bytes)
        assertNull(legacy.last)
        destination.clear()
        assertEquals(12, AndroidSystemTrustRootsV1(source(arrayOf(legacy))).copyInto(destination, written) { false })
        assertEquals(0, written[0])
        for(i in 0 until destination.capacity()) assertEquals(0, destination.get(i).toInt())
    }
    @Test fun publicCertificateVectorCrossesTheActualNativeParserContract() {
        // Fixed public Ed25519 CA, generated by the evidence-only vector script.
        // Native TestMaintenanceAndroidKotlinRootsVector independently consumes these bytes.
        val der = Base64.getDecoder().decode("MIIBNTCB6KADAgECAgICrDAFBgMrZXAwIjEgMB4GA1UEAxMXVGFzazZiNGIgcHVibGljIGZpeHR1cmUwHhcNMjYwMTAxMDAwMDAwWhcNMjcwMTAxMDAwMDAwWjAiMSAwHgYDVQQDExdUYXNrNmI0YiBwdWJsaWMgZml4dHVyZTAqMAUGAytlcAMhADtqJ7zOtqQtYqOo0CpvDXNlMhV3HeJDpjrASKGLWdopo0IwQDAOBgNVHQ8BAf8EBAMCAgQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUE545QOZLVJFyIIjZoNdBYo/IJuAwBQYDK2VwA0EAYhxZZuAcsksi9XWzHDZodEoGI6UZqZJXLPztwRtBAaGrvEFPEbbM2yHyZcjxUROvTN/vimREjV1BwCWWG3IwCg==")
        val cert = CertificateFactory.getInstance("X.509").generateCertificate(der.inputStream()) as X509Certificate
        assertEquals("CN=Task6b4b public fixture", cert.subjectX500Principal.name)
        val dst = ByteBuffer.allocateDirect(der.size + 7)
        val written = intArrayOf(99)
        assertEquals(0, AndroidSystemTrustRootsV1(source(arrayOf(cert))).copyInto(dst, written) { false })
        assertEquals(320, written[0])
        val bytes = ByteArray(written[0]); dst.get(bytes)
        assertArrayEquals(byteArrayOf(1, 0, 1, 0, 0, 1, 57), bytes.copyOfRange(0, 7))
        assertArrayEquals(der, bytes.copyOfRange(7, bytes.size))
        val encoded = Base64.getEncoder().encodeToString(bytes)
        assertEquals("AQABAAABOTCCATUwgeigAwIBAgICAqwwBQYDK2VwMCIxIDAeBgNVBAMTF1Rhc2s2YjRiIHB1YmxpYyBmaXh0dXJlMB4XDTI2MDEwMTAwMDAwMFoXDTI3MDEwMTAwMDAwMFowIjEgMB4GA1UEAxMXVGFzazZiNGIgcHVibGljIGZpeHR1cmUwKjAFBgMrZXADIQA7aie8zrakLWKjqNAqbw1zZTIVdx3iQ6Y6wEihi1naKaNCMEAwDgYDVR0PAQH/BAQDAgIEMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFBOeOUDmS1SRciCI2aDXQWKPyCbgMAUGAytlcANBAGIcWWbgHLJLIvV1sxw2aHRKBiOlGamSVyz87cEbQQGhq7xBTxG2zNsh8mXI8VETr0zf74pkRI1dQcAllhtyMAo=", encoded)
        println("KOTLIN_ROOTS_VECTOR=" + encoded)
    }

    @Test fun managerAmbiguityAndExactCapacityBoundaries() {
        val selections = listOf(
            emptyArray<TrustManager>(),
            arrayOf<TrustManager>(Manager(arrayOf(Certificate(1))), Manager(arrayOf(Certificate(1)))),
            arrayOf<TrustManager>(object : TrustManager {}),
        )
        for (managers in selections) {
            val roots = AndroidSystemTrustRootsV1(AndroidSystemTrustRootsSourceV1 {
                AndroidSystemTrustSelectionV1("AndroidNSSP", managers, "android.security.net.config.RootTrustManager")
            })
            val dst = ByteBuffer.allocateDirect(8); dst.put(0, 99)
            val written = intArrayOf(99)
            assertEquals(12, roots.copyInto(dst, written) { false })
            assertEquals(0, written[0]); for (i in 0 until 8) assertEquals(0, dst.get(i).toInt())
        }
        // 3-byte header + 64 length fields + 63*16384 + 16125 = 1048576.
        for ((last, expected) in listOf(16125 to 0, 16126 to 6)) {
            val certs = Array<X509Certificate>(64) { Certificate(if (it == 63) last else 16384) }
            val dst = ByteBuffer.allocateDirect(1048576); val written = intArrayOf(99)
            assertEquals(expected, AndroidSystemTrustRootsV1(source(certs)).copyInto(dst, written) { false })
            assertEquals(if (expected == 0) 1048576 else 0, written[0])
            if (expected != 0) for (i in 0 until dst.capacity()) assertEquals(0, dst.get(i).toInt())
        }
        val written = intArrayOf(99)
        assertEquals(0, AndroidSystemTrustRootsV1(source(Array(512) { Certificate(1) }))
            .copyInto(ByteBuffer.allocateDirect(2563), written) { false })
        assertEquals(2563, written[0])
        var sourceReads = 0
        val unavailable = AndroidSystemTrustRootsV1(AndroidSystemTrustRootsSourceV1 { sourceReads++; error("source") })
        val dst = ByteBuffer.allocateDirect(8)
        assertEquals(8, unavailable.copyInto(dst, written) { true }); assertEquals(0, sourceReads)
        assertEquals(12, unavailable.copyInto(dst, written) { false }); assertEquals(1, sourceReads)
        assertEquals(0, written[0]); for (i in 0 until 8) assertEquals(0, dst.get(i).toInt())
    }

    private class Certificate(private val size: Int, private val fail: Boolean = false, private val serial: BigInteger = BigInteger.ONE) : X509Certificate() {
        var last: ByteArray? = null
        override fun getEncoded(): ByteArray {
            check(!fail)
            return ByteArray(size) { 0x30 }.also { last = it }
        }
        override fun checkValidity() = Unit
        override fun checkValidity(date: Date) = Unit
        override fun getVersion() = 3
        override fun getSerialNumber(): BigInteger = serial
        override fun getIssuerDN(): Principal = Principal { "test" }
        override fun getSubjectDN(): Principal = Principal { "test" }
        override fun getNotBefore() = Date(0)
        override fun getNotAfter() = Date(1)
        override fun getTBSCertificate() = byteArrayOf()
        override fun getSignature() = byteArrayOf()
        override fun getSigAlgName() = "test"
        override fun getSigAlgOID() = "1.2.3"
        override fun getSigAlgParams(): ByteArray? = null
        override fun getIssuerUniqueID(): BooleanArray? = null
        override fun getSubjectUniqueID(): BooleanArray? = null
        override fun getKeyUsage(): BooleanArray? = null
        override fun getBasicConstraints() = -1
        override fun verify(key: PublicKey) = Unit
        override fun verify(key: PublicKey, provider: String) = Unit
        override fun getPublicKey(): PublicKey? = null
        override fun hasUnsupportedCriticalExtension() = false
        override fun getCriticalExtensionOIDs(): Set<String>? = null
        override fun getNonCriticalExtensionOIDs(): Set<String>? = null
        override fun getExtensionValue(oid: String): ByteArray? = null
        override fun toString() = "TestCertificate"
    }
    private class Manager(private val issuers: Array<X509Certificate>) : X509TrustManager {
        override fun getAcceptedIssuers() = issuers
        override fun checkClientTrusted(chain: Array<X509Certificate>, authType: String) = Unit
        override fun checkServerTrusted(chain: Array<X509Certificate>, authType: String) = Unit
    }
    private fun source(certificates: Array<X509Certificate>, provider: String = "AndroidNSSP", name: String = "android.security.net.config.RootTrustManager") =
        AndroidSystemTrustRootsSourceV1 { AndroidSystemTrustSelectionV1(provider, arrayOf<TrustManager>(Manager(certificates)), name) }

    @Test fun exactFramingUsesOneTemporaryAndWipesIt() {
        val first = Certificate(2); val second = Certificate(3)
        val roots = AndroidSystemTrustRootsV1(source(arrayOf(first, second)))
        val destination = ByteBuffer.allocateDirect(16)
        val written = intArrayOf(99)
        assertEquals(0, roots.copyInto(destination, written) { false })
        assertEquals(16, written[0])
        val bytes = ByteArray(16); destination.get(bytes)
        assertArrayEquals(byteArrayOf(1,0,2,0,0,0,2,0x30,0x30,0,0,0,3,0x30,0x30,0x30), bytes)
        assertTrue(first.last!!.all { it == 0.toByte() }); assertTrue(second.last!!.all { it == 0.toByte() })
    }

    @Test fun limitsAmbiguityEncodingAndCancellationWipePartialOutput() {
        val cases = listOf(
            source(emptyArray()) to 12,
            source(Array(513) { Certificate(1) }) to 6,
            source(arrayOf(Certificate(16385))) to 6,
            source(arrayOf(Certificate(0))) to 12,
            source(arrayOf(Certificate(1)), provider = "other") to 12,
            source(arrayOf(Certificate(1)), name = "other") to 12,
            source(arrayOf(Certificate(2), Certificate(1, true))) to 12,
            source(Array(64) { Certificate(16384) }) to 6,
        )
        for ((source, expected) in cases) {
            val dst = ByteBuffer.allocateDirect(1048576)
            for (i in 0 until dst.capacity()) dst.put(i, 0x6a)
            val written = intArrayOf(7)
            assertEquals(expected, AndroidSystemTrustRootsV1(source).copyInto(dst, written) { false })
            assertEquals(0, written[0])
            for (i in 0 until dst.capacity()) assertEquals(0, dst.get(i).toInt())
        }
        val roots = AndroidSystemTrustRootsV1(source(arrayOf(Certificate(2), Certificate(3))))
        val dst = ByteBuffer.allocateDirect(16); val written = intArrayOf(7)
        var checks = 0
        assertEquals(8, roots.copyInto(dst, written) { ++checks > 2 })
        assertEquals(0, written[0]); for (i in 0 until 16) assertEquals(0, dst.get(i).toInt())
    }

    @Test fun malformedViewStillWipesWholeBorrowedCapacityWithoutThrowing() {
        val roots = AndroidSystemTrustRootsV1(source(arrayOf(Certificate(2))))
        val dst = ByteBuffer.allocateDirect(16)
        for (i in 0 until 16) dst.put(i, 0x5a)
        dst.limit(4)
        val written = intArrayOf(9)
        assertEquals(1, roots.copyInto(dst, written) { false })
        assertEquals(0, written[0])
        assertEquals(4, dst.limit())
        val full = dst.duplicate().apply { clear() }
        for (i in 0 until 16) assertEquals(0, full.get(i).toInt())
    }
}
