import {config} from '../../site.config.mjs';
import {validateClaim} from '../lib/core.mjs';
export const sourceUrl=(path)=>`${config.source}/blob/${config.revision}/${path}`;
export const sources={
  readme:sourceUrl('README.md'),
  ctl:sourceUrl('cmd/kurdctl/main.go'),
  selfhost:sourceUrl('docs/self-hosting/QUICKSTART.md'),
  security:sourceUrl('docs/self-hosting/SECURITY.md'),
  strings:sourceUrl('android/core/ui/src/main/res/values/strings.xml'),
  home:sourceUrl('android/feature/home/src/main/kotlin/org/kurdistanvpn/feature/home/HomeScreen.kt'),
  license:sourceUrl('LICENSE'),
  mark:sourceUrl('website/public/kurdistan-mark.svg'),
  releases:`${config.source}/releases`,
};
const inventory=[
 {id:'owner',status:'AVAILABLE',wording:'The deployment owner controls the VPS and deployment authority.',meaning:'Kurdistan VPN is software for independently operated deployments, not a shared server subscription.',mechanism:'The operator runs kurd-node and uses kurdctl for local authority, profile issuance, revocation and recovery.',limit:'A person using a profile may not be its owner. You still trust that operator, the hosting provider and the software.',evidence:[sources.readme,sources.security]},
 {id:'account',status:'AVAILABLE',wording:'No required central Kurdistan VPN account.',meaning:'The product architecture does not require a central product login or public relay directory.',mechanism:'An owner-issued profile and an explicitly confirmed deployment fingerprint establish the intended relationship.',limit:'This does not mean anonymous use. A VPS host, deployment operator or another service can have its own account requirements.',evidence:[sources.readme]},
 {id:'trust',status:'AVAILABLE',wording:'Profile validity and owner trust are separate decisions.',meaning:'A valid signature is not proof that a profile came from the person you intended.',mechanism:'The Android import flow previews the profile, requires comparison of the deployment fingerprint, and confirms storage.',limit:'You need an independent, trusted way to compare the fingerprint. A code repeated by the same untrusted sender is not independent confirmation.',evidence:[sources.readme,sources.strings]},
 {id:'storage',status:'AVAILABLE',wording:'Android profile storage is designed around local encryption.',meaning:'The reviewed Android foundation uses encrypted storage backed by Android Keystore.',mechanism:'Sensitive profile admission is bounded; the app accesses verification through a native Go bridge.',limit:'The browser preview is not that secure store. A compromised device or unsafe backup can still expose information.',evidence:[sources.readme]},
 {id:'privacy',status:'AVAILABLE',wording:'No required product advertising or analytics service.',meaning:'Independent deployments do not depend on a Kurdistan advertising, analytics or remote crash-reporting service.',mechanism:'The repository specifies local custody and categorical, secret-safe diagnostics rather than central traffic logging.',limit:'This does not establish a logging policy for every operator or VPS host. The website has its own, separate privacy notice.',evidence:[sources.readme,sources.security]},
 {id:'scope',status:'EXPERIMENTAL',wording:'Runtime choices are bounded by the signed profile.',meaning:'The app may narrow a verified plan, not invent a relay, strategy or fallback outside it.',mechanism:'The compiler/runtime implements authenticated stream semantics, policy checks, replay and downgrade checks.',limit:'Source and controlled tests do not establish leak prevention on every phone. Android lockdown is a separate system policy.',evidence:[sources.readme,sources.home]},
 {id:'dns',status:'EXPERIMENTAL',wording:'The engineering path is designed to keep DNS inside the tunnel.',meaning:'DNS policy belongs to the authenticated connection, not an opportunistic public-resolver fallback.',mechanism:'The Phase 17 engineering package documents a Kurd TLS relay and TUN-scoped resolver policy.',limit:'The public production egress path and broad device validation are not established as released. This is not a blanket DNS-leak guarantee.',evidence:[sources.selfhost,sources.security,sources.home]},
 {id:'simple',status:'EXPERIMENTAL',wording:'Grandma Mode demonstrates a simpler interface.',meaning:'Large text, fewer choices and guided help offer another view of the same connection model.',mechanism:'The supplied design prototype contains Home / Help / Settings and explicit setup and recovery steps.',limit:'This is design-prototype evidence, not proof that this exact experience ships in an available APK. Translation review and real-user studies remain necessary.',evidence:['src/prototype/app.html']},
 {id:'release',status:'UNQUALIFIED',wording:'A production Android download is not established.',meaning:'There is no production APK offered by this website.',mechanism:'The reviewed README explicitly marks the software pre-release; the releases API returned no published releases at review.',limit:'The source snapshot is not a live status feed. Check the repository for newer, independently verifiable release evidence.',evidence:[sources.readme,sources.releases]},
 {id:'audit',status:'UNQUALIFIED',wording:'Internal tests are not an independent security audit.',meaning:'The repository includes substantial regression and assurance tooling.',mechanism:'Adversarial, mutation, parity and security checks are described in the source.',limit:'No independent release-candidate audit report was established in the reviewed evidence. No certification or third-party assurance is claimed.',evidence:[sources.readme]},
 {id:'website',status:'VERIFIED',wording:'This website build contains no analytics or advertising integration.',meaning:'Reading these pages does not require a third-party script, remote font service or tracking cookie.',mechanism:'Static documents and local assets; preferences stay in browser storage when available. Search runs locally.',limit:'Verified by local source/runtime inspection only. The eventual hosting provider receives web requests; its log retention requires an operator policy.',evidence:['src/client/site.js','docs/QA_REPORT.md']},
 {id:'future',status:'PLANNED',wording:'Wider platform and operational validation remains future work.',meaning:'A roadmap is not a claim that a feature protects users today.',mechanism:'Release gates must bind source, artifacts, signatures and exact-build qualification before public download claims change.',limit:'There is no release date, delivery guarantee or supplementary-protocol support promise.',evidence:[sources.readme]},
];
export const claims=inventory.map(c=>({...c,owner:'Project maintainers',reviewed:config.reviewed,release:null}));
claims.forEach(validateClaim);
export const claimById=id=>claims.find(c=>c.id===id);
export const stateLabels={AVAILABLE:'Implemented in source',VERIFIED:'Locally checked website',EXPERIMENTAL:'Engineering / design preview',PLANNED:'Planned',UNQUALIFIED:'Not established'};
