import {config} from '../../site.config.mjs';
import {sources} from './claims.mjs';
import {link,note,table,code,technical,proof} from '../components/primitives.mjs';
const s=(id,title,body)=>({id,title,body});
export const docsPages=[
 {slug:'docs',title:'Kurdistan VPN documentation — profiles, operation and verification',heading:'Start with the job<br>you need to do.',description:'Source-grounded Kurdistan VPN documentation for profiles, device enrollment, self-hosting, DNS, recovery and build verification.',category:'Documentation',eyebrow:'DOCUMENTATION',lead:'Practical paths first. Technical detail, source references and limits stay close to each step.',social:'docs',sections:[
 s('start','Using a profile',c=>`<div class="doc-links">${link('I received a profile',c.p('docs/profile'))}${link('Prepare a device enrollment request',c.p('docs/enrollment'))}${link('Understand a connection problem',c.p('help'))}${link('Use the simpler interface',c.p('simple'))}</div>`),
 s('operate','Operating a deployment',c=>`<div class="doc-links">${link('Self-hosting overview',c.p('self-host'))}${link('Keep authority and keys separate',c.p('docs/keys'))}${link('Rotation and revocation',c.p('docs/revocation'))}${link('Backup and recovery',c.p('docs/recovery'))}</div>`),
 s('inspect','Inspecting the system',c=>`<div class="doc-links">${link('DNS and routing boundaries',c.p('docs/dns-routing'))}${link('Build and test from source',c.p('docs/build'))}${link('Verify an artifact',c.p('verify'))}${link('Security assumptions',c.p('trust/model'))}</div>`),
 s('version','These guides have a source boundary',()=>`<p>Reviewed source: <code dir="ltr">${config.revision}</code> on branch <code dir="ltr">${config.branch}</code>. The guides describe pre-release source and engineering procedures, not a currently supported consumer release.</p><p>Commands have been checked against repository documentation. They were not run against a VPS or a physical Android device as part of building this website.</p>`),
 ],related:['download','help','trust'],sources:['readme','selfhost']},
 {slug:'docs/profile',title:'Import and verify a Kurd profile on Android',heading:'Check the profile.<br>Confirm the person.',description:'Follow Kurd profile preview, recipient checks, deployment fingerprint comparison and explicit storage confirmation without confusing validity with owner trust.',category:'Documentation',eyebrow:'DOCS / PROFILES',lead:'A profile carries permission to use a deployment. Do not treat an unfamiliar profile as trustworthy just because it imports.',social:'docs',sections:[
 s('before','Before you begin',()=>`${note('Use the intended Android build','The public production APK is not established in the reviewed release evidence. This guide explains the source workflow; the website preview accepts demonstration data only.','warning')}<p>You need a profile from a deployment owner you intend to trust, the correct recipient device when sealed, and a separately trusted way to compare the owner’s full deployment fingerprint.</p>`),
 s('steps','Preview → compare → confirm',()=>`<ol class="numbered"><li><h3>Choose the import explicitly</h3><p>Open Profiles, then the add or QR action. The source supports bounded file, URI, clipboard, share-intent and QR admission. Do not paste production profiles into a website mockup.</p></li><li><h3>Review the profile</h3><p>Read the preview and any recipient, expiry or validity issue. A mismatched device or failed validation must not be bypassed.</p></li><li><h3>Compare the deployment fingerprint</h3><p>Use the complete code and an independently trusted channel to the intended owner. Do not compare only the first or last few characters.</p></li><li><h3>Confirm trust and storage</h3><p>Nothing should be silently accepted merely because you opened an import. Confirmation stores the accepted profile locally.</p></li><li><h3>Select it, then return Home</h3><p>Profile management and connection control are separate jobs. The Home state must reflect the actual runtime, not the animation.</p></li></ol>`),
 s('outcome','What changed?',()=>table(['Outcome','What to expect'],[['Accepted','The intended local profile is available for selection after explicit confirmation.'],['Duplicate','The existing copy stays unchanged. Do not repeatedly re-import it.'],['Older generation','Rollback checks reject an older replacement rather than silently downgrading.'],['Wrong device or invalid signature','Stop. Ask the owner for an appropriate signed profile for this device.'],['Revoked or expired','Changing the display, system clock or interface mode is not a way to restore authority.']])),
 s('trust','Validity is not identity',()=>proof('trust',true)),
 ],related:['docs/enrollment','help/profile-expired','help/fingerprint'],sources:['readme','strings']},
 {slug:'docs/enrollment',title:'Device enrollment and recipient-sealed Kurd profiles',heading:'A public request.<br>A profile for this device.',description:'Understand Android device enrollment, public requests, private key custody and owner-issued recipient-sealed Kurd profiles.',category:'Documentation',eyebrow:'DOCS / DEVICE ENROLLMENT',lead:'The phone prepares a public request. The deployment owner uses it to issue a profile intended for that device.',social:'docs',sections:[
 s('prerequisites','Before creating a request',()=>`<p>Use a compatible Android engineering build and an owner-operated deployment. Device storage must be healthy. Do not silently replace an invalidated key or confuse a browser demonstration with real enrollment.</p>`),
 s('flow','Which part runs where?',()=>table(['Where','Action and effect'],[['Android device','Create a device-owned public enrollment request. Private material stays in protected encrypted local storage.'],['Trusted transfer channel','Give the exact public request to the intended deployment owner. A recipient request is single-use by default in the guide.'],['Owner’s VPS / administration system','Issue the recipient-sealed profile with kurdctl. The Android app never receives root administration authority.'],['Intended Android device','Import the returned profile. Preview, compare deployment identity, then confirm storage.']])),
 s('sharing','Public does not mean “send anywhere”',()=>`<p>The Android resource text says the enrollment export is public-only and contains no private key. Share it only with the owner who will issue the intended profile.</p><p>Documentation uses a <code dir="ltr">.kurd-enrollment</code> input path while source UI strings label an <code dir="ltr">Export .kurd-recipient</code> action. These are retained as a documented naming inconsistency; do not invent a universal extension rule from the mismatch.</p>`),
 s('failure','When the key is missing or invalidated',c=>`<p>Preserve the existing state. A sealed profile for another device cannot be made appropriate by renaming it. Ask the owner for the correct recipient-bound profile or follow an explicit recovery path.</p>${link('Read recovery guidance',c.p('docs/recovery'))}`),
 ],related:['self-host','docs/profile','docs/keys'],sources:['readme','selfhost','strings']},
 {slug:'self-host',title:'Self-host Kurdistan VPN on an owner-controlled VPS',heading:'Your deployment.<br>Your responsibility.',description:'A source-backed Kurd node engineering workflow: verify a package, establish local authority, enroll a device, issue a sealed profile and preserve recovery material.',category:'Documentation',eyebrow:'SELF-HOST / ENGINEERING GUIDE',lead:'You operate the server and hold the deployment authority. The Android app remains a client—not a remote VPS administration panel.',social:'self-host',sections:[
 s('boundary','Read the engineering boundary first',()=>`${note('Pre-release, not a one-click production service','The Phase 17 package documents an authenticated Kurd TLS/TCP relay. It remains unsigned until its distribution gate and has not completed the external data-path acceptance campaign in the reviewed guide.','warning')}<p><strong>You need:</strong> a supported 64-bit Linux system with systemd, administration access, a trusted workstation, the intended engineering archive and separately authenticated verification information. The owner must understand backups, permissions, clock handling and recovery.</p>`),
 s('verify','01 — Verify before extracting',()=>`<p><strong>Runs on:</strong> a trusted workstation. Obtain the archive and its separately authenticated SHA-256. The package verifier must be available.</p>${code('kurdpackage verify --archive <archive>','host-verify')}<p><strong>Changes:</strong> verifies a local archive, not the live server. <strong>Success:</strong> a successful verifier exit for the intended archive and an identity match with trusted publication information. <strong>On failure:</strong> stop and obtain the correct package; do not skip verification.</p><p>Extract into a new empty directory and inspect <code dir="ltr">manifest.json</code>, <code dir="ltr">SHA256SUMS</code> and the scripts.</p>`),
 s('install','02 — Install without silently starting',()=>`<p><strong>Runs on:</strong> the owner’s Linux system, inside the verified extracted directory. Inspect the scripts and their prerequisites first.</p>${code('sudo ./preflight.sh --install\nsudo ./install.sh --install','host-install')}<p><strong>Changes:</strong> installs the engineering package. The guide explicitly says installation does not create authority keys, enable the listener or start the service.</p><p><strong>Success:</strong> preflight and installation complete without errors. If preflight fails, correct its reported prerequisite rather than enabling the listener manually.</p>`),
 s('authority','03 — Establish local authority and recovery',()=>`<p><strong>Runs on:</strong> the owner system after installation. The exact flags below were checked in <code dir="ltr">cmd/kurdctl/main.go</code>, not inferred from a marketing example.</p><p>First define the non-secret shell variables <code dir="ltr">DEPLOYMENT_NAME</code>, <code dir="ltr">RELAY_ENDPOINT</code> (host:port) and <code dir="ltr">RECOVERY_FILE</code> for the intended deployment. The recovery file must be in a protected location outside <code dir="ltr">/var/lib/kurd-node</code>, writable by the service user.</p>${code('sudo -u kurd-node /usr/local/bin/kurdctl init \\\n  --data-dir /var/lib/kurd-node \\\n  --name "$DEPLOYMENT_NAME" \\\n  --endpoint "$RELAY_ENDPOINT" \\\n  --recovery-file "$RECOVERY_FILE"','host-init')}<p><strong>Changes:</strong> initializes deployment identity and writes the encrypted recovery artifact. <strong>Success:</strong> the command returns <code dir="ltr">kurdctl-init-v1</code> output with the deployment identifier, root fingerprint, recovery path and a recovery-confirmation next step. Those values are not supplied by this website.</p>${note('Passphrases are standard input, not flags','Use a controlled, non-logging standard-input procedure. The source does not establish a no-echo interactive prompt here: do not type a passphrase into an echoing shared terminal, store it in an environment variable, or include it in shell history.','warning')}${code('sudo -u kurd-node /usr/local/bin/kurdctl recovery confirm \\\n  --data-dir /var/lib/kurd-node \\\n  --recovery-file "$RECOVERY_FILE"\nsudo -u kurd-node /usr/local/bin/kurdctl doctor \\\n  --data-dir /var/lib/kurd-node','host-doctor')}<p>Recovery confirmation reads the passphrase on standard input again. A successful response has <code dir="ltr">confirmed: true</code>; the doctor command requires an overall <code dir="ltr">PASS</code>. On failure, preserve the current state. Do not silently reinitialize or delete the recovery artifact.</p>${link('Inspect the actual command implementation',sources.ctl,'text-link',true)}`),
 s('enroll','04 — Prepare the intended device',c=>`<p>Export a fresh public enrollment request from the Android app. Transfer the exact request to the owner through an authenticated channel. The request lets the owner issue a profile for that device; it does not give the app administration powers.</p>${link('Follow device enrollment',c.p('docs/enrollment'))}`),
 s('issue','05 — Issue a recipient-sealed profile',()=>`<p><strong>Runs on:</strong> the owner’s configured VPS, as the <code dir="ltr">kurd-node</code> service user. <strong>Prerequisites:</strong> healthy local authority, the intended public request and a new empty output directory. Replace the request path with the actual intended file.</p>${code('sudo -u kurd-node /usr/local/bin/kurdctl profile create \\\n  --data-dir /var/lib/kurd-node \\\n  --name phone \\\n  --valid-for 168h \\\n  --recipient-request /path/to/device.kurd-enrollment \\\n  --recipient-registry-dir /var/lib/kurd-node/recipient-registry \\\n  --output-dir /var/lib/kurd-node/export-phone','host-issue')}<p><strong>Changes:</strong> issues a profile under the deployment’s authority and recipient policy. The output is sensitive. Transfer only the intended profile or QR to the intended device; remove temporary copies after import.</p><p><strong>Success:</strong> the command completes and the intended device can verify the resulting artifact. A generated file alone is not proof of end-to-end Internet access. On failure, inspect safe diagnostics; do not weaken recipient or signature checks.</p>`),
 s('activate','06 — Enable only after checks pass',()=>`<p><strong>Runs on:</strong> the owner’s VPS with system administration authority. <strong>Prerequisites:</strong> preflight and local checks passed; appropriate network policy and recovery material are in place.</p>${code('sudo systemctl enable --now kurd-node-network.service kurd-node.socket\nsudo systemctl start kurd-node.service\nsudo systemctl is-active kurd-node.service kurd-node.socket','host-activate')}<p><strong>Changes:</strong> enables the documented network policy, socket and service. <strong>Success:</strong> service and socket report active. That only establishes service status—not production egress qualification.</p><p><strong>Failure:</strong> do not open arbitrary firewall access or disable authentication. Use the operator guide and safe diagnostics. No speculative repair command is offered here.</p>`),
 s('finish','07 — Verify the deployment; preserve recovery',c=>`<p>On the intended phone, import and verify the profile, compare the deployment fingerprint and explicitly confirm trust. Keep encrypted recovery material and current encrypted backups off the VPS. Losing both is unrecoverable according to the quickstart.</p><p>Do not claim successful Internet egress until the exact build passes the namespace, emulator and owner-VPS evidence gates. This website has not executed those campaigns.</p>${link('Read the security boundary',sources.security,'text-link',true)}${link('Understand backup and recovery',c.p('docs/recovery'))}`),
 ],related:['docs/enrollment','docs/keys','verify'],sources:['selfhost','security','readme','ctl']},
 {slug:'docs/keys',title:'Deployment authority and key custody — Kurdistan VPN',heading:'Keep the keys<br>with their actual owners.',description:'Distinguish deployment root, online issuer, relay identity and Android device keys in the Kurdistan VPN self-hosting model.',category:'Documentation',eyebrow:'DOCS / KEY CUSTODY',lead:'A single “encrypted” label hides too much. The source describes distinct roles with different custody and recovery requirements.',social:'security',sections:[
 s('roles','Four roles that must not be collapsed',()=>table(['Role','Documented custody'],[['Deployment root','Unique to one owner; private key exists only in the passphrase-encrypted recovery artifact.'],['Online issuer','Encrypted owner-only local state; issues under deployment-local authority.'],['Relay identity','Encrypted owner-only local state for the owner’s relay.'],['Android device material','Protected local storage; a public enrollment request supports recipient-sealed profile issuance.']])),
 s('operator','The client must not become the operator',()=>`<p>Root recovery material, operator credentials, administrative commands and deployment-wide authority do not belong in a mobile profile, public QR or casual support bundle.</p><p>The self-hosting security guide describes software key custody. Hardware-backed operator adapters are not a current requirement or a feature to imply through marketing.</p>`),
 s('handling','Handle recovery deliberately',()=>`<p>Do not put passphrases in arguments, environment variables or shell history. Keep recovery material off the VPS. Run <code dir="ltr">kurdctl doctor</code> after clock changes, storage recovery, upgrades or permission changes.</p><p>The guide says a clock repair requires the offline recovery artifact. Do not improvise a clock or signature bypass to make an expired profile connect.</p>`),
 ],related:['docs/enrollment','docs/recovery','trust/model'],sources:['security','selfhost','readme']},
 {slug:'docs/revocation',title:'Profile generations, rotation and revocation — Kurdistan VPN',heading:'Access can change.<br>Identity must stay explicit.',description:'Understand signed profile generations, rotation, expiry, revocation and the limits of one deployment’s authority.',category:'Documentation',eyebrow:'DOCS / PROFILE LIFECYCLE',lead:'The owner can change access within their deployment. An app preference is not permission to undo that decision.',social:'docs',sections:[
 s('states','Different changes need different explanations',()=>table(['State','Meaning and next step'],[['Expiry','The profile is no longer valid for starting a session. Ask the owner for the appropriate newer signed profile.'],['Rotation','A newer signed generation can replace the local record through a reviewed, confirmed flow.'],['Revocation','The deployment owner has withdrawn access. Do not retry around the decision or weaken validation.'],['Duplicate or rollback','Preserve the existing copy; do not silently replace it with the same or an older generation.'],['Deployment-local disable','Applies to that independent deployment and advances its signed revocation state. It is not a project-wide shutdown authority.']])),
 s('changes','Changing the interface changes no authority',()=>`<p>Switching theme, language, text size or Grandma Mode must not change the active profile, its validity or the runtime’s security checks.</p><p>Imported updates must remain authenticated and scoped. An arbitrary subscription URL is not sufficient to establish trust.</p>`),
 s('help','The next step stays concrete',c=>`<p>Keep the saved profile until the reason is understood. Ask the intended owner for a replacement or use another already verified, valid profile. Never make a “temporarily ignore checks” control part of recovery.</p>${link('Help with an expired profile',c.p('help/profile-expired'))}${link('Help with a withdrawn profile',c.p('help/profile-revoked'))}`),
 ],related:['docs/profile','docs/recovery','trust'],sources:['readme','security','strings']},
 {slug:'docs/dns-routing',title:'DNS, routes and Android lockdown boundaries — Kurdistan VPN',heading:'Separate the path<br>from the platform policy.',description:'Understand the Kurd engineering DNS path, per-app routing, signed plan boundaries and why Android lockdown is a separate authority.',category:'Documentation',eyebrow:'DOCS / DNS AND ROUTING',lead:'A configured preference, an active authenticated session and Android’s system blocking policy are three different facts.',social:'security',sections:[
 s('dns','DNS follows the authenticated path',()=>`<p>The engineering design keeps DNS in the Kurd session. The self-hosting security guide describes Unbound accepting only the TUN client pools. The app must not silently substitute a public resolver when a trusted path fails.</p>${proof('dns',true)}`),
 s('routing','Application eligibility is not a promise of connection',()=>`<p>The Android source model supports all-app, include-only and exclude-selected routing policies. Changing an active per-app policy requires re-establishing the interface; changing a checkbox alone is not evidence that the installed routing table changed.</p><p>An excluded application may use traffic outside the VPN unless the operating system blocks it. A route preview must distinguish VPN-eligible, direct and system-blocked outcomes rather than labelling all of them protected.</p>`),
 s('lockdown','Android controls Android’s blocking policy',()=>`${note('Do not overstate fail-closed behaviour','A runtime rejecting an invalid session does not prove device-wide blocking in every lifecycle state. Android always-on and lockdown state must be reported truthfully.','warning')}<p>Use the actual system settings to inspect platform-managed operation. A website or browser prototype cannot grant VPN permission, enable system lockdown or establish a native VPN interface.</p>`),
 s('scope','Unqualified options do not become functional by appearing in a UI',()=>`<p>The supplied prototype includes capability inspection pages for wider resolver modes, supplementary protocols and routing rules. Those pages preserve scope for future work; they are not a list of supported production features.</p>`),
 ],related:['trust/model','docs/recovery','help/phone-restarted'],sources:['readme','security','home','strings']},
 {slug:'docs/recovery',title:'Backups and deliberate recovery — Kurdistan VPN',heading:'Preserve first.<br>Recover deliberately.',description:'Understand encrypted backups, device recovery, owner recovery and why verification must never be weakened to restore a connection.',category:'Documentation',eyebrow:'DOCS / RECOVERY',lead:'When storage or trust cannot be proven, a quiet interface should explain the next step—not silently recreate keys or reset a deployment.',social:'docs',sections:[
 s('first','Before changing anything',()=>`<p>Keep the existing encrypted state where possible. Read the failure category. Distinguish a missing device key, an invalidated device key, an expired profile, revoked permission and damaged local storage.</p><p>Do not post raw logs, full profiles, secrets, DNS questions or browsing destinations in a public issue. Use a previewed, redacted diagnostic summary where the native workflow supports it.</p>`),
 s('two','Device backups and deployment recovery are different',()=>table(['Boundary','Recovery responsibility'],[['Android device','Use a supported encrypted-backup and explicit restore flow. Review the intended records before applying. A browser-demo backup is not an Android recovery artifact.'],['Deployment owner','Keep the encrypted root recovery artifact and current encrypted backups off the VPS. The owner controls deployment recovery.'],['Website preview','Only synthetic demo state is involved. It cannot recover real keys, profiles or a VPS.']])),
 s('stop','Do not weaken a check to get connected',()=>`<p>Certificate, signature, expiry, revocation, replay, downgrade and rollback checks must not be weakened for convenience. The remedy for an inappropriate profile is an appropriate owner-issued one, not a hidden bypass.</p>${note('No automatic repair promise','The reviewed evidence does not establish complete recovery for every Android lifecycle or physical device. Restarting the phone is not proof that a protected tunnel has returned.','warning')}`),
 s('operator','Checks after an owner operation',()=>`${code('kurdctl doctor --data-dir /var/lib/kurd-node','recovery-doctor')}<p><strong>Where:</strong> the configured owner system. <strong>When:</strong> after clock changes, storage recovery, upgrades or permission changes. <strong>Effect:</strong> inspect local consistency; it is not a generic permission to reset or re-key.</p><p>On failure, preserve state and follow the source guide. The guide requires the offline recovery artifact for clock repair.</p>`),
 ],related:['help/phone-restarted','docs/keys','help/safe-diagnostics'],sources:['readme','security','strings']},
 {slug:'docs/build',title:'Build and test Kurdistan VPN from source',heading:'A successful build<br>is a starting point.',description:'Source-documented Kurdistan compiler and Android engineering build commands, prerequisites and their qualification limits.',category:'Documentation',eyebrow:'DOCS / SOURCE BUILD',lead:'The commands here build or test the VPN source. They are separate from the commands used to build this static website.',social:'docs',sections:[
 s('requirements','Use the source’s declared toolchain',()=>`<p>The reviewed README requires Go 1.26.6 or newer in the Go 1.26 line, Git, and JDK 17 with Android SDK 36 for Android builds. Treat these as the requirements of the pinned source—not claims about your installed tools.</p><p>Run the following commands from a checkout of that repository, not from this website project.</p>`),
 s('gate','Run the complete repository gate',()=>`${code('go run ./cmd/gate\n# Include the Android host gate\ngo run ./cmd/gate -android','source-gate')}<p><strong>Where:</strong> the repository root. <strong>Effect:</strong> runs module verification, compilation, vet, uncached tests and applicable audit/product gates according to the README. <strong>Success:</strong> each invoked gate completes successfully.</p><p>A focused test or a compile pass is not equivalent to this gate. This website work did not execute the VPN gate or qualify a runtime.</p>`),
 s('android','Create an Android internal build',()=>`${code('cd android\n./gradlew :app:assembleInternal --no-build-cache','android-build')}<p><strong>Where:</strong> Linux or macOS development machine with the declared JDK/SDK. On Windows the documented wrapper invocation is:</p>${code('cd android\n.\\gradlew.bat :app:assembleInternal --no-build-cache','android-windows','powershell')}<p><strong>Changes:</strong> generates an internal Android artifact in the source build environment. Internal trust fixtures are not public release material. A compiled APK must not be relabelled as a production release without the appropriate gates.</p>`),
 s('compiler','A deterministic compiler exercise',()=>`${code('go run ./cmd/kdc generate --seed 12345 --out profile.json\ngo run ./cmd/kdc validate --profile profile.json','compiler-example')}<p><strong>Where:</strong> the repository root with the Go toolchain. <strong>Changes:</strong> creates and validates a deterministic compiler profile. Keep generated sensitive deployment material out of source control unless it is an explicitly non-secret fixture.</p><p><strong>Success:</strong> generation and validation succeed. This is not a sealed Android profile issuance procedure or proof of Internet egress.</p>`),
 s('failure','When something fails',()=>`<p>Record the exact source revision, toolchain and categorical error. Correct the underlying build or test problem. Do not disable security assertions, package verification or profile checks to obtain a green result.</p>`),
 ],related:['verify','releases','contribute'],sources:['readme']},
];
