/* Build-checked interface messages; text nodes, never injected HTML. */
export const clientMessages = [
  "Kurdistan VPN app demo. No network protection.",
  "Loading the local design preview…",
  "The preview did not become ready. The product explanation and help links still work.",
  "Retry preview",
  "App demo: {state}. No VPN traffic.",
  "Preview ready. All data and VPN activity are simulated.",
  "This reference points outside the app demo. ",
  "View on GitHub",
  "Automatic copy is unavailable. The command is selected for manual copying.",
  "Copied",
  "Command copied",
  "Command copied. Read the prerequisites before running it.",
  "Copy",
  "Offline saving needs HTTPS or localhost. Use your browser’s Save page or Print instead.",
  "Saving public guides on this device…",
  "Guides saved on this device. They are dated copies, not live release information.",
  "The guides could not be saved. Your VPN is unchanged. Check the connection or use Save page.",
  "Saved website guides removed. No VPN or profile settings changed.",
  "Browser storage settings prevented removal. Remove this website’s data in your browser settings.",
  "Your browser did not save this preference. It still applies to this page.",
  "Website appearance changed. Your VPN is unchanged.",
  "Reading preferences updated. Your VPN is unchanged.",
  "Full website restored. Your VPN is unchanged.",
  "Choose the local file you want to check.",
  "This local tool accepts files up to 64 MiB. Use a local command-line utility for a larger file.",
  "Enter exactly 64 hexadecimal characters for the expected SHA-256 checksum.",
  "This browser context does not provide Web Crypto. Use HTTPS, localhost or a local SHA-256 utility. Nothing was uploaded.",
  "Computing SHA-256 locally…",
  "The checksums match.",
  "The checksums do not match.",
  "The file matches the expected bytes. This does not verify the publisher’s identity, a signature or the safety of the software.",
  "Do not treat this file as the expected artifact. Check its source and the independently obtained expected checksum.",
  "The file could not be read or hashed. Choose it again or use a local utility. Nothing was uploaded.",
  "No matching explanation.",
  "Try profile, permission, DNS or self-hosting. Nothing was submitted or changed.",
  "Loading the local search index…",
  "{count} results. Search stays on this device.",
  "The first 35 are shown.",
  "The search index could not be loaded. Use the full search page or navigation. No query was sent.",
  "Ownership boundaries"
];
