import {phase3Home} from '../phase3/home.mjs';
import {config} from '../../site.config.mjs';
import {sources,claims} from './claims.mjs';
import {architecture,ownerExplorer,demo,checksumTool} from '../components/experiences.mjs';
import {link,note,proof,table,technical,code,sun,icon} from '../components/primitives.mjs';
import {docsPages} from './docs.mjs';
import {helpPages} from './help.mjs';
const s=(id,title,body)=>({id,title,body});
export const mainPages=[
 {slug:'',title:'Made for restricted networks — Kurdistan VPN',description:'Free, open-source VPN software for restricted networks. Explore Kurd, profiles, self-hosting and privacy, and try the interactive app.',category:'Product',social:'product',custom:phase3Home,sources:['readme','security','strings','selfhost']},
 {slug:'how-it-works',title:'How Kurdistan VPN works',heading:'How your connection works',description:'Follow the device, signed profile, Kurd connection and owner-controlled relay. Understand what each layer controls and what the model does not guarantee.',category:'Product',eyebrow:'THE MODEL',lead:'One architecture, explained at two depths. Start with the relationship; open the details when they become useful.',social:'self-host',sections:[
 s('path','From your phone to the VPN server',c=>architecture(c)),
 s('sequence','Three decisions before a connection',c=>`<ol class="numbered"><li><h3>Receive a profile</h3><p>The server operator gives you a profile for your device. The Kurdistan VPN project does not run a central server subscription.</p></li><li><h3>Check it, then decide whom to trust</h3><p>Profile verification checks the artifact. Comparing the full deployment fingerprint with the owner checks the relationship you intended.</p></li><li><h3>Use only the permitted path</h3><p>The app must stay inside the signed profile’s authority. It cannot silently invent a new relay or direct fallback.</p></li></ol>${note('Engineering boundary','This describes the design and reviewed source. The public production Internet-egress path is not established as a released build.','warning')}`),
 s('ownership','Who controls each part?',()=>ownerExplorer()),
 s('depth','What makes the protocol profile-driven?',()=>technical('<p>Kurdistan compiles bounded protocol behaviour from a profile: framing, state transitions, scheduling, padding, probing, carrier policy and permitted fallback can vary while retaining authenticated stream semantics.</p><p>This is not permission for the client to select arbitrary transports. Every runtime choice stays inside the verified plan. Source presence does not prove censorship bypass or undetectability.</p>')+proof('scope')),
 ],related:['docs/profile','trust','self-host'],sources:['readme','selfhost','home']},
 {slug:'trust',title:'Security model and trust boundaries — Kurdistan VPN',heading:'Check what the evidence supports.',description:'Inspect Kurdistan VPN claims, supporting source and limitations. Distinguish implemented source, engineering previews and unestablished production evidence.',category:'Security',eyebrow:'TRUST CENTRE',lead:'Read each claim alongside its source and limitations. Implementation, testing and release qualification are different things.',social:'security',sections:[
 s('evidence','What each status actually means',()=>table(['Status','Meaning'],[['Implemented in source','A capability is described and represented in the reviewed repository. Not a production qualification.'],['Locally checked website','A property of this website build was checked locally. Not an audit of the VPN.'],['Engineering / design preview','Controlled source behaviour or a supplied interface demonstration.'],['Planned','Intent or a future gate, not current protection.'],['Not established','The reviewed evidence does not support the stronger claim.']])),
 s('claims','See the evidence behind the claims',()=>claims.map(c=>proof(c.id)).join('')),
 s('limits','What the evidence does not establish',c=>`<p>We do not claim guaranteed anonymity, undetectability, successful censorship bypass, universal leak prevention, an independent security audit or a production-ready Android release.</p>${link('Read assumptions and threat boundaries',c.p('trust/model'))}${link('Understand release verification',c.p('verify'))}`),
 s('report','Found a security concern?',c=>`<p>The repository asks for private reporting to its owner rather than a public issue containing exploit details or secrets. This site does not invent a security inbox or response promise.</p>${link('Read the reporting guidance',c.p('security-report'))}`),
 ],related:['trust/model','privacy','verify'],sources:['readme','security','home']},
 {slug:'trust/model',title:'Threat assumptions, keys and failure boundaries — Kurdistan VPN',heading:'Know what remains in the trust model.',description:'Device compromise, deployment operators, hosting providers, software and release provenance remain distinct trust boundaries in Kurdistan VPN.',category:'Security',eyebrow:'TRUST / SECURITY MODEL',lead:'Owner operation moves control. It does not remove the need to trust devices, software, operators or hosting infrastructure.',social:'security',sections:[
 s('assumptions','Who you still need to trust',()=>table(['Boundary','What remains your responsibility'],[['Your device','Protect device access and backups. Local encryption is not protection against every compromised-device scenario.'],['Deployment owner','Choose the intended owner and compare their fingerprint independently. An operator can revoke access to their own deployment.'],['Hosting provider','A VPS is hosted on someone’s infrastructure. Do not infer an absence of hosting logs or visibility from a product architecture claim.'],['Software and updates','Inspect source, build provenance and exact artifact identity. Open source alone is not an independent audit.'],['Internet services','A VPN is not a guarantee of anonymity to sites you sign in to, or immunity from all traffic analysis.']])),
 s('keys','Three kinds of custody',()=>`<p>The source describes a deployment-local root, an online issuer and a relay identity. The root private key belongs in the passphrase-encrypted recovery artifact. Online issuer and relay keys live in owner-only encrypted local state.</p><p>Android device enrollment is different: the phone exports a public request so the owner can issue a recipient-sealed profile. The client does not become the deployment administrator.</p>${technical('<p>The self-hosting security guide explicitly describes software key custody, not a mandatory hardware-backed TPM, PKCS#11 or HSM arrangement. Do not market optional future adapters as current hardware security.</p>')}`),
 s('failure','Fail closed is not a blanket phone-wide promise',c=>`<p>The runtime is designed to reject invalid authority rather than bypass signature, expiry, replay or revocation checks. That is distinct from Android’s system-level control over traffic outside the VPN.</p>${note('Keep the distinction','A stopped session is not a connected session. Without confirmed system blocking, do not tell a user that every other application is unable to use the network.','warning')}${link('Read DNS and routing boundaries',c.p('docs/dns-routing'))}${link('Read recovery guidance',c.p('docs/recovery'))}`),
 s('assurance','What has not been established',()=>`<p>The repository describes internal adversarial, mutation, parity and security test tooling. The reviewed material does not establish independent release-candidate assurance or broad physical-device and hosting-provider validation.</p><p>This page is a source-backed explanation of assumptions, not a new formal threat-model certification or an independent assessment of the implementation.</p>`),
 ],related:['trust','docs/enrollment','security-report'],sources:['readme','security','selfhost']},
 {slug:'product',title:'Explore the Kurdistan VPN Android design',heading:'Your profiles, clearly organized.',description:'Try the supplied Kurdistan VPN Android design prototype, including profile groups, deployment trust, connection states and Grandma Mode. All activity is simulated.',category:'Product',eyebrow:'ANDROID / DESIGN PROTOTYPE',lead:'The interface makes state visible, keeps profile management compact and reveals technical detail when you ask for it.',social:'product',sections:[
 s('preview','Use the design, not a slideshow',c=>demo(c)),
 s('principles','A distinct job for each destination',()=>table(['Destination','Its job'],[['Home','See the connection state, selected profile and the next connection action.'],['Profiles','Find, group, inspect and select profiles. There is no connection toggle on the Profiles page.'],['Settings','Configure the interface and inspect connection, privacy and recovery boundaries.'],['Grandma Mode','See one clear state, one obvious action and persistent Home / Help / Settings navigation.']])),
 s('trust','Important choices are not hidden',c=>`<p>Import preview, fingerprint comparison and confirmation are separate steps. An unusable profile gets a reason and a next action—not a cosmetic “secure” badge.</p>${proof('simple')}${link('Explore the simpler experience',c.p('simple'))}`),
 ],related:['download','simple','docs/profile'],sources:['strings','home','readme']},
 {slug:'simple',title:'Grandma Mode — a simpler Kurdistan VPN interface',heading:'A simpler view,<br>when you need it.',description:'Explore the inclusive Grandma Mode design: large text, clear state, guided setup and help. Demonstration, not a claim of released APK availability.',category:'Product',eyebrow:'GRANDMA MODE / INCLUSIVE DESIGN',lead:'Larger text, fewer choices and clear next steps. Choose it when you prefer less interface.',social:'simple',sections:[
 s('website','Make this website simpler',()=>`<p>Grandma Mode changes this website, not your VPN. The main navigation becomes Home, Android app and Help. Full explanations remain available under More details or Use full website.</p><label class="check-control website-simple-toggle" data-enhance><input type="checkbox" data-grandma><span>Use Grandma Mode on this website</span></label>`),
 s('everyday','The everyday questions come first',()=>`<div class="simple-example"><div>${sun()}<h3>VPN is off.</h3><p>Turn it on when you are ready.</p></div><div><h3>Home. Help. Settings.</h3><p>Large controls stay in predictable places. Status always has words as well as colour. Technical settings remain available to a helper through a deliberate return to the full interface.</p></div></div>`),
 s('guided','One decision at a time',()=>`<ol class="numbered"><li><h3>Get your setup</h3><p>A link, file or QR code from the person helping you.</p></li><li><h3>Check who it came from</h3><p>Compare the complete safety code with that person before accepting the setup.</p></li><li><h3>Review, then save</h3><p>Nothing is silently replaced simply because you opened the setup flow.</p></li><li><h3>Get an exact next step</h3><p>Help distinguishes a phone permission issue, an expired setup, a restart and an unreliable connection.</p></li></ol>`),
 s('try','Try the simplified design',c=>demo(c,'grandma')),
 s('status','What this preview proves—and does not',()=>proof('simple',true)),
 ],related:['accessibility','help','product'],sources:['strings','readme']},
 {slug:'download',title:'Kurdistan VPN for Android — availability and release status',heading:'Before there is a download,<br>there must be evidence.',description:'Check the source-grounded Kurdistan VPN Android release status. No production APK, invented checksum or unverified download is offered.',category:'Releases',eyebrow:'ANDROID / AVAILABILITY',lead:'The reviewed project is pre-release. This website does not offer a production APK or pretend that a source build is a public release.',social:'releases',sections:[
 s('availability','No production Android artifact is offered here',()=>`<div class="availability"><span class="status-pill">${icon('info')}Pre-release</span><h3>Source available.<br>Production download not established.</h3><p>The releases API returned no published releases at the review date. There is no APK version, publication date, file size, checksum or signature to display as an official release.</p></div>${table(['Field','Verified display boundary'],[['Platform','Android foundation'],['Minimum Android source target','API 26+ in the reviewed README'],['Production artifact','Not available from this website'],['Public release version / date','Not established'],['Artifact hash / signature','Not supplied; not fabricated'],['Source snapshot',`<code dir="ltr">${config.revision}</code>`],['Reviewed',config.reviewed]])}`),
 s('what-exists','What is in the source',()=>`<p>The compiler, authenticated runtime components, signed-profile tooling, Android foundation and owner-operated node administration are represented in the repository.</p><p>The engineering package contains a Kurd TLS/TCP relay, but the documentation separates this from an accepted public production data path. Compiling successfully is not proof of operational readiness.</p>${proof('release')}`),
 s('next','Choose the next step that matches your role',c=>`<div class="journey-links">${link('I want to try the design',c.p('product'))}${link('I already received a profile',c.p('docs/profile'))}${link('I want to build from source',c.p('docs/build'))}${link('I want to verify an artifact',c.p('verify'))}${link('Check the repository’s releases',sources.releases,'text-link',true)}</div>`),
 ],related:['releases','verify','docs/build'],sources:['readme','selfhost','releases']},
 {slug:'releases',title:'Release evidence and project status — Kurdistan VPN',heading:'A release is more than a version number.',description:'Check public Kurdistan VPN releases, source revisions and artifact verification. No invented release or download is offered.',category:'Releases',eyebrow:'RELEASES / SOURCE SNAPSHOT',lead:'This is a dated evidence snapshot, not a live feed. The repository remains the place to check for newer releases.',social:'releases',sections:[
 s('current','No public releases returned at review',()=>`<p>On ${config.reviewed}, the connected GitHub releases endpoint returned an empty array. A newer source branch is not automatically a new Android release.</p>${table(['Layer','What the reviewed evidence supports'],[['Foundation','Compiler, authority, profile tooling and Android foundations described in source.'],['Engineering','Authenticated relay implementation is available for controlled validation, not a qualified public service.'],['Public release','Production APK, accepted public egress and completed distribution evidence not established.']])}`),
 s('revision','The source revision used for this website',()=>`<p>Reviewed branch: <code dir="ltr">${config.branch}</code>.</p><p>Commit: <code dir="ltr">${config.revision}</code>, dated ${config.sourceDate}. That source date is not a release publication date.</p>${link('Inspect the exact source revision',`${config.source}/tree/${config.revision}`,'text-link',true)}`),
 s('future-record','What a future release record must contain',()=>`<p>Before enabling a public download, maintainers must bind the artifact to its source revision, release channel, date, minimum platform, checksum, signing evidence, changes, known issues and migration notes.</p><p>Records for withdrawn artifacts should explain withdrawal without silently redirecting to an unrelated download. This build has no withdrawn release to invent.</p>`),
 ],related:['download','verify','trust'],sources:['readme','releases']},
 {slug:'verify',title:'Verify a Kurdistan VPN artifact and compare SHA-256',heading:'Verify the artifact.<br>Not just the button.',description:'Understand source, build, artifact, checksum and signature boundaries. Compare a local SHA-256 checksum without uploading your file.',category:'Releases',eyebrow:'RELEASE INTEGRITY',lead:'A matching checksum checks bytes. It does not prove who published them, or that the software is safe.',social:'releases',sections:[
 s('chain','The chain you need to establish',()=>`<ol class="provenance-chain"><li>Source</li><li>Build</li><li>Artifact</li><li>Checksum</li><li>Signature & evidence</li></ol><p>The reviewed repository does not establish a complete public distribution chain. Do not treat the diagram above as a claim that each link has been qualified.</p>${note('No official checksum is prefilled','There is no production APK offered by this website. Obtain any expected hash through a separately trusted source.','warning')}`),
 s('compare','Compare a file locally',()=>`<p>The optional tool below uses your browser’s SHA-256 implementation. The selected file stays in memory on your device; it is not sent to this website or a server. Only files up to 64 MiB are accepted.</p>${checksumTool()}`),
 s('native','The engineering package has its own verification command',()=>`<p><strong>Where:</strong> a trusted workstation, with the project’s package verifier available. <strong>Prerequisite:</strong> the engineering archive and a separately authenticated expected checksum.</p>${code('kurdpackage verify --archive <archive>','verify-command')}<p><strong>Effect:</strong> inspect the archive, rather than install or start the node. Replace <code dir="ltr">&lt;archive&gt;</code> with the intended path.</p><p><strong>Success:</strong> the verifier exits successfully for the intended package; compare its identity with trusted publication information. <strong>Failure:</strong> stop and obtain the intended artifact. Do not bypass verification.</p><p>This command was checked against the source guide, not executed against a VPN release during this website build.</p>`),
 ],related:['download','docs/build','self-host'],sources:['selfhost','readme']},
 {slug:'privacy',title:'Product privacy and website privacy — Kurdistan VPN',heading:'Privacy needs a scope.',description:'Understand the difference between Kurdistan VPN architecture, an operator’s deployment, and the public website’s data handling.',category:'Privacy',eyebrow:'PRIVACY',lead:'“No required central service” is not the same as “nobody can see anything.” Here is what each part of the system means.',social:'security',sections:[
 s('questions','Start with the ordinary questions',c=>table(['Question','Answer'],[['Do I need a Kurdistan account?','The reviewed product architecture does not require a central Kurdistan account. A deployment owner or host may have separate requirements.'],['Where are app profiles kept?','The Android foundation describes locally encrypted, Keystore-backed storage. The browser preview uses synthetic records, not a secure profile vault.'],['Does the product require analytics?','No analytics, advertising or remote crash-reporting service is required by the reviewed design.'],['What can my VPS see?','The owner and hosting provider remain in your trust model. Do not infer an operator log policy or universal anonymity guarantee from this website.'],['Does this website track me?',`This build contains no analytics, advertising, fingerprinting or session replay integration. ${link('Read website privacy',c.p('privacy/website'))}`],['Who receives a support summary?','No website support upload exists. Review and explicitly share only redacted material with the intended recipient.']])),
 s('product','The product boundary',()=>proof('privacy',true)+proof('storage')),
 s('operator','Your operator is a separate party',()=>`<p>A deployment owner controls the profile and the server. The project’s decentralised model does not certify the behaviour, retention policy or security of every independently operated deployment.</p><p>Ask the operator what they retain, who hosts the server and how they handle revocation and recovery. Use encrypted application protocols where appropriate; a VPN does not replace them.</p>`),
 ],related:['privacy/website','trust/model','docs/recovery'],sources:['readme','security']},
 {slug:'privacy/website',title:'Website privacy — Kurdistan VPN',heading:'A small website footprint.',description:'What this website build stores locally, what it sends, and what remains a hosting-provider policy. No trackers or third-party embeds are required.',category:'Privacy',eyebrow:'PRIVACY / THIS WEBSITE',lead:'This notice describes the website code delivered in this project. It is separate from the VPN and from the eventual host’s operational logging policy.',social:'security',sections:[
 s('requests','What a visit sends',()=>`<p>Your browser requests static pages and assets from the site host. That host necessarily receives request information such as your IP address, request time and requested path. This project cannot establish its live retention policy before deployment.</p><p>This website code does not send requests to analytics, advertising, third-party font, search, chat or session-replay services. External documentation and GitHub links open only when you choose them.</p>`),
 s('local','What stays in your browser',()=>table(['Feature','Local handling'],[['Appearance preferences','Theme, contrast and text preferences may be stored under the website’s local-storage key. The site still works if storage is blocked.'],['Search','The static local index is filtered in your browser. Queries are not submitted to a search service.'],['Checksum comparison','The selected file and expected hash are processed locally. They are not uploaded or stored by this website.'],['Interactive preview','The preview runs in a sandbox without same-origin access or network access. It uses synthetic state and has no access to the parent website’s storage.'],['Offline reading','When you explicitly save guides, a service worker caches a small, fixed set of public documents and required assets. Release artifacts, credentials and the prototype are excluded. You can remove the cache from Offline reading.'],['Cookies','This website code does not set cookies. Review host-added behaviour before publishing.']])),
 s('inspect','Inspect the deployed files',c=>`<p>The build manifest lists the exact local files and their SHA-256 values. It is a way to inspect this website snapshot, not a signed software release or an independent privacy audit.</p>${link('Open the website build manifest',c.base+'BUILD_MANIFEST.json')}${link('Read the deployed page and asset index',c.base+'build-info.json')}<p>The website source and build tools are available in the public repository.</p>`),
 s('control','Your controls',()=>`<p>Use Preferences to change or reset the local appearance preference. Browser site-data controls also remove it. The website does not require registration, marketing consent or a tracking-cookie choice.</p><button class="button secondary" data-reset-preferences data-enhance>Reset website preferences</button><p role="status" data-preference-status class="caption"></p>`),
 s('deployment','Before a public deployment',()=>`<p>The operator must confirm its hosting/CDN logs, actual response headers, retention, legal identity and any additional policy required for its jurisdiction. No legal-compliance certification is asserted by this technical notice.</p>`),
 ],related:['privacy','about','security-report'],sources:[]},
 {slug:'accessibility',title:'Accessibility and inclusive interaction — Kurdistan VPN website',heading:'Clarity is an accessibility feature.',description:'Read the website accessibility approach, available reading controls, keyboard behaviour and the limits of local automated verification.',category:'Product',eyebrow:'ACCESSIBILITY',lead:'The goal is an understandable next step—whether you use a keyboard, a phone, larger text or the simpler app design.',social:'simple',sections:[
 s('controls','Read in the way that works for you',()=>`<p>Use Preferences for light, dark or system appearance, larger text and stronger contrast. Browser zoom is not disabled. Reduced-motion preferences remove spatial transitions; all information remains available without animation.</p><p>Important standalone controls have at least 44-pixel targets. Native document headings, landmarks, form labels, details and links provide the foundation before JavaScript enhances anything.</p>`),
 s('keyboard','A predictable keyboard path',()=>`<p>The first Tab exposes Skip to content. Header navigation, search and preferences are reachable without a pointer. Search can open with Control/Command + K; Escape closes the dialog and returns focus to the control that opened it.</p><p>The ownership explorer supports arrow keys, Home and End when enhanced. With JavaScript disabled, every boundary remains readable as ordinary page content.</p>`),
 s('evidence','What has been checked',()=>`<p>The public test suite checks browser behavior, responsive layout, keyboard controls, contrast and reduced motion. Automated checks do not establish full WCAG conformance or replace assistive-technology testing.</p>${note('Remaining human verification','Screen-reader sessions, native-language review, older-adult usability studies and physical-device testing remain release checks. No accessibility certification is claimed.')}`),
 ],related:['simple','help','about'],sources:[]},
 {slug:'about',title:'About Kurdistan VPN — source, ownership and project boundaries',heading:'About Kurdistan VPN.',description:'Learn the Kurdistan VPN project model, source and licensing, brand identity and current release limitations.',category:'Project',eyebrow:'ABOUT THE PROJECT',lead:'Kurdistan VPN is a profile-driven, self-hosted relay transport project. This website explains its model without presenting engineering work as a mature commercial service.',social:'product',sections:[
 s('identity','A Kurdish identity, used with restraint',()=>`<div class="about-identity">${sun()}<span class="flag-signature" role="img" aria-label="Red, white and green brand signature"><i></i><i></i><i></i></span></div><p>The website retains the repository’s original K-shaped mark and uses the Kurdish sun’s 21-ray geometry as a quiet connection and ownership motif. Most of the interface remains neutral; colour is reserved for meaning.</p><p>This is not a claim of government affiliation, certification or sponsorship.</p>`),
 s('source','Open source is an invitation to inspect',()=>`<p>The repository is licensed under AGPL-3.0-or-later. Read the source, the local-authority model, the test inventory and the current limitations—not just the homepage.</p>${link('Open the source repository',config.source,'button primary',true)}${link('Read the project license',sources.license,'text-link',true)}`),
 s('web-evidence','About this website build',()=>`<p>Built from a reviewed source snapshot dated ${config.sourceDate}, with evidence reviewed on ${config.reviewed}. The website has its own version, ${config.websiteVersion}; this is not a VPN or APK release number.</p><p>The public repository contains website source, build tools and tests. A website version is separate from an Android app release.</p>`),
 ],related:['contribute','releases','privacy/website'],sources:['readme','license','mark']},
 {slug:'contribute',title:'Contribute to Kurdistan VPN — code, review and translation',heading:'Help improve the project.',description:'Find source, contribution boundaries, translation-review needs and security-reporting guidance for Kurdistan VPN.',category:'Project',eyebrow:'CONTRIBUTE',lead:'Useful contributions preserve the project’s authority boundaries, honest capability descriptions and reproducible evidence.',social:'docs',sections:[
 s('code','Code and technical review',()=>`<p>The README asks for narrowly scoped, behaviour-preserving changes unless an intentional change is being proposed. Include focused regression checks; the full project gate remains separate from a focused pass.</p>${link('Read contribution guidance in the README',sources.readme,'text-link',true)}<p>Do not post real profiles, credentials, endpoints, recovery artifacts or traffic logs in public issues.</p>`),
 s('language','Native-language review matters',c=>`<p>This website is available in English, Sorani and Kurmanji. Native-speaker review is still needed to check the translations in use.</p><p>Review terminology, tone, punctuation, mixed-script technical strings and the plain language used in help. Report unclear wording with the page address and the meaning you expected.</p>${link('Read localization status',c.p('languages'))}`),
 s('security','Security findings need a private path',c=>`<p>The repository directs researchers to report security issues privately to its owner. Do not use an ordinary public issue to submit exploit details or secrets.</p>${link('Read the reporting boundary',c.p('security-report'))}`),
 ],related:['docs/build','languages','security-report'],sources:['readme']},
 {slug:'security-report',title:'Report a security concern — Kurdistan VPN',heading:'Report privately.<br>Do not expose the people affected.',description:'Source-backed security reporting guidance for Kurdistan VPN, including the absence of a verified dedicated inbox, response SLA or bounty promise.',category:'Security',eyebrow:'RESPONSIBLE DISCLOSURE',lead:'The reviewed README asks you to contact the repository owner privately instead of opening a public issue containing exploit details or secrets.',social:'security',sections:[
 s('channel','A reporting limitation worth stating clearly',()=>`${note('Dedicated channel not established','The reviewed sources do not supply a verified security email address, encryption key, response SLA or bounty programme. This website will not invent one.','warning')}<p>Use an already trusted private channel to the owner. When no such channel is available, ask the maintainer how to establish one without disclosing the vulnerability. Check the repository for a newer security policy before sending details.</p>${link('Check repository security information',config.source+'/security','button secondary',true)}`),
 s('include','What helps once a private channel is established',()=>`<p>Provide the affected source revision or artifact identity, the security boundary involved, safe reproduction steps and the expected versus observed behaviour. Keep reproduction fixtures synthetic where possible.</p><p>Do not casually send credentials, private keys, complete profiles, browsing history, DNS questions or other people’s data. Agree on a safe transfer method for genuinely necessary sensitive evidence.</p>`),
 s('website','Website issues versus VPN issues',()=>`<p>Identify whether a finding concerns this static website, the supplied design demonstration, the Android client, the Kurd runtime or a particular owner-operated deployment. They are not the same security boundary.</p><p>This guidance does not promise a response deadline or permission to test somebody else’s deployment.</p>`),
 ],related:['trust/model','contribute','privacy/website'],sources:['readme']},
 {slug:'languages',title:'Read Kurdistan VPN in your language',heading:'English. Sorani. Kurmanji.',description:'Choose your language for every public page, guide, search and website Grandma Mode. Language choice stays on this device.',category:'Project',eyebrow:'LANGUAGES',lead:'Choose the language you want to read. The website does not choose it from your location.',social:'docs',sections:[
 s('choose','Choose your language',c=>`<nav class="locale-page-links" aria-label="Choose language">${[['en','English'],['ckb','کوردی (سۆرانی)'],['kmr','Kurdî (Kurmancî)']].map(([l,label])=>`<a href="${c.p('',l)}" data-language-choice="${l}" lang="${l}" dir="${l==='ckb'?'rtl':'ltr'}"><img src="${c.a('flag-'+(l==='en'?'uk':'kurdistan')+'.svg')}" width="36" height="24" alt=""><span data-no-translate>${label}</span>${icon('arrow','directional')}</a>`).join('')}</nav>`),
 s('reading','The same pages in each language',()=>`<p>Navigation, guides, search, help and website Grandma Mode are available in all three languages. Sorani reads from right to left. Commands, file names and technical identifiers keep their original spelling.</p><p>The app demonstration is a separate supplied reference. Some of its engineering screens retain their original language.</p>`),
 s('review','Help us improve a translation',()=>`<p>Translations have been checked for coverage, layout and terminology. They have not been approved by a native human reviewer. Report unclear wording with the page address and the meaning you expected.</p>`),
 ],related:['contribute','accessibility'],sources:[]},
 {slug:'license',title:'Licenses and asset provenance — Kurdistan VPN website',heading:'Keep the source<br>and its provenance together.',description:'Project license, Kurdistan VPN identity, website code and attribution for distributed assets.',category:'Project',eyebrow:'LICENSES / PROVENANCE',lead:'The public source includes license notices and attribution for distributed assets.',social:'docs',sections:[
 s('upstream','Project and original mark',()=>`<p>The upstream repository declares AGPL-3.0-or-later. Its README carries CC-BY-SA-4.0 notices. The original K mark is retained from <code dir="ltr">website/public/kurdistan-mark.svg</code>; no affiliation beyond the supplied project identity is invented.</p>${link('Read the upstream license',sources.license,'text-link',true)}${link('Inspect the original mark',sources.mark,'text-link',true)}`),
 s('website','This website project',()=>`<p>The website source is available under AGPL-3.0-or-later. Preserve license and attribution notices when redistributing. The interactive app is an isolated demonstration, not a VPN connection.</p><p>The site serves bundled fonts and their notices locally, without a remote font service. Browser-test tools are separate from the deployed static files.</p>`),
 ],related:['about','contribute'],sources:['license','mark']},
];
export const pages=[...mainPages,...docsPages,...helpPages];
