import {link,note,icon} from '../components/primitives.mjs';
import {escape as e} from '../lib/core.mjs';
export function utilityPages(all){return [
 {slug:'search',title:'Search Kurdistan VPN documentation and help',heading:'Find the next explanation.',description:'Search local Kurdistan VPN help, documentation, product, privacy and release explanations without a third-party search service.',category:'Help',eyebrow:'SITE SEARCH',lead:'Search is local. Without JavaScript, the complete linked index below is still available.',social:'docs',sections:[{id:'index',title:'Documentation, help and evidence',body:c=>`<div class="search-page-form" data-enhance><label for="page-search">Search the website</label><input id="page-search" type="search" autocomplete="off" placeholder="Profile expired, DNS, install node…"><p id="page-search-status" role="status">Search stays on this device.</p></div><div data-page-results><ul class="search-results">${all.map(p=>`<li><a href="${c.p(p.slug)}" class="search-result"><small>${e(p.category)}</small><strong>${e(p.title)}</strong><p>${e(p.description)}</p></a></li>`).join('')}</ul></div>`}],sources:[]},
 {slug:'offline',title:'Offline reading — Kurdistan VPN',heading:'A guide should still help<br>when the network does not.',description:'Save selected public Kurdistan VPN guides for offline reading. Cached documentation is a dated source snapshot, not live release information.',category:'Help',eyebrow:'OFFLINE READING',lead:'You can keep a small set of public explanations on this device. Nothing from the VPN, your profiles or the interactive prototype is saved by this feature.',social:'docs',sections:[
  {id:'save',title:'Keep the essential guides',body:()=>`${note('Cached pages are a snapshot','Offline copies can become stale. Check the live source before operating a deployment or trusting a release. No APK, credential or profile is cached.','warning')}<div data-enhance class="action-row"><button class="button primary" data-offline-save>Save guides for offline reading ${icon('file')}</button><button class="button secondary" data-offline-remove>Remove saved guides</button></div><p data-offline-status role="status" class="caption"></p><noscript><p>Use your browser’s Save page or Print function to keep a public guide locally. Automatic guide caching is optional and needs JavaScript.</p></noscript>`},
  {id:'included',title:'What is included',body:c=>`<div class="doc-links">${[['Profile import','docs/profile'],['Device enrollment','docs/enrollment'],['Backup and recovery','docs/recovery'],['Help index','help'],['Privacy boundaries','privacy']].map(([title,path])=>link(title,c.p(path))).join('')}</div><p>The offline cache also contains the required local styles and scripts. Download/release pages are not cached as if they were live evidence.</p>`},
 ],related:['docs','help','privacy/website'],sources:[]},
 ...[['404','This page is not here.','The address does not match a page in this website. No profile, setting or file has been changed.'],['unavailable','This resource is not available.','The requested resource cannot be provided here. No download was started and nothing on your device has changed.'],['failure','This page could not be opened.','The request could not be completed. Your VPN and saved setup are not controlled by this website.']].map(([slug,heading,description])=>({slug,title:heading+' — Kurdistan VPN',description,category:'Help',error:true,social:'docs',custom:c=>`<section class="wrap error-page"><p class="error-number">${slug==='404'?'404 / PAGE NOT FOUND':'RESOURCE / UNAVAILABLE'}</p><h1>${heading}</h1><p>${description}</p><div class="action-row">${link('Search the documentation',c.p('search'),'button primary')}${link('Return Home',c.p(''),'button secondary')}</div>${link('Check Android availability',c.p('download'))}</section>`})),
 ];}
