import {config} from '../../site.config.mjs';
import {escape as e,pathFor} from '../lib/core.mjs';
import {locales,navRoutes} from '../content/locales.mjs';
import {sources} from '../content/claims.mjs';
import {icon,link,sun} from './primitives.mjs';
import {localizeHTML,t} from '../i18n/translate.mjs';
import {clientMessages} from '../content/interface.mjs';
export function makeContext(locale,base){return {locale,base,p:(slug='',chosen)=>pathFor(slug,chosen||locale,base),a:name=>base+'assets/'+name};}
const labels=['How it works','Trust','Self-host','Docs','Android & releases'];
function brand(ctx){return `<a class="brand" href="${ctx.p('')}" aria-label="Kurdistan VPN · Home"><img src="${ctx.a('kurdistan-mark.svg')}" width="30" height="30" alt=""><span data-no-translate>Kurdistan <strong>VPN</strong></span></a>`;}
function languageMenu(ctx,page){return `<details class="language-menu"><summary aria-label="Choose language"><img src="${ctx.a('flag-'+locales[ctx.locale].flag+'.svg')}" width="24" height="16" alt=""><span class="language-label" data-no-translate>${locales[ctx.locale].name}</span>${icon('chevron','menu-chevron')}</summary><nav class="language-panel" aria-label="Choose language">${Object.entries(locales).map(([code,l])=>`<a href="${ctx.p(page.slug,code)}" lang="${code}" dir="${l.dir}" data-language-choice="${code}"${ctx.locale===code?' aria-current="page"':''}><img src="${ctx.a('flag-'+l.flag+'.svg')}" width="30" height="20" alt=""><span data-no-translate dir="${l.dir}">${l.name}</span>${ctx.locale===code?icon('check'):''}</a>`).join('')}</nav></details>`;}
function preferences(){return `<details class="preferences"><summary aria-label="Reading preferences">${icon('settings')}<span class="tool-label">Preferences</span></summary><div class="preferences-panel"><h2>Make yourself comfortable.</h2><fieldset data-enhance><legend>Appearance</legend><div class="segmented">${['system','light','dark'].map(v=>`<button type="button" data-theme-choice="${v}" aria-pressed="false">${v[0].toUpperCase()+v.slice(1)}</button>`).join('')}</div><label class="check-control"><input type="checkbox" data-grandma><span><strong>Grandma Mode</strong><small>A simpler website, with larger text and fewer choices.</small></span></label><label class="check-control"><input type="checkbox" data-contrast> Stronger contrast</label><label class="check-control"><input type="checkbox" data-larger-text> Larger text</label><label class="check-control"><input type="checkbox" data-reduced-motion> Less movement</label></fieldset><p class="caption">These choices stay in this browser. They do not change your VPN.</p><button class="text-link full-site-control" data-full-site data-enhance>Use full website ${icon('arrow')}</button><noscript><p>Your device theme is used automatically. Manual preferences need JavaScript.</p></noscript></div></details>`;}
function github(){return `<a class="github-link" href="${config.source}" target="_blank" rel="noopener noreferrer" aria-label="View Kurdistan VPN on GitHub">${icon('github')}<span>View on GitHub</span></a>`;}
function header(ctx,page){return `<div id="top" class="page-top" tabindex="-1"></div><header class="site-header"><div class="header-inner wrap">${brand(ctx)}<nav class="desktop-nav full-navigation" aria-label="Main navigation">${navRoutes.slice(0,4).map((r,i)=>`<a href="${ctx.p(r)}"${page.slug===r?' aria-current="page"':''}>${labels[i]}</a>`).join('')}</nav><nav class="simple-navigation" aria-label="Simple website navigation">${[['Home',''],['Android app','download'],['Help','help']].map(([label,r])=>`<a href="${ctx.p(r)}"${page.slug===r?' aria-current="page"':''}>${label}</a>`).join('')}</nav><div class="header-tools"><a class="search-opener icon-link" href="${ctx.p('search')}" data-search-open aria-label="Search the website">${icon('search')}</a>${languageMenu(ctx,page)}${preferences()}<div class="header-github full-navigation">${github()}</div><details class="mobile-menu full-navigation"><summary>${icon('menu')}<span>Menu</span></summary><nav aria-label="Mobile navigation">${navRoutes.map((r,i)=>`<a href="${ctx.p(r)}">${labels[i]}</a>`).join('')}<a href="${ctx.p('help')}">Help</a>${github()}</nav></details></div></div></header>`;}
export const principles=[
 ['Open source','Read the implementation. Build it, test it, improve it. The code is open under the AGPL license.'],
 ['No ads or analytics','No advertising, behavioral tracking, or surveillance-based business model. This website does not send analytics.'],
 ['Self-hosted','Each operator runs their own infrastructure and controls their own keys, connection profiles, backups, and data.'],
 ['No central switch','Independent deployments do not rely on a product-wide authority, relay directory, or mandatory Kurdistan account.'],
];
export const dedication='Kurdistan VPN (کوردستان ڤی‌پی‌ئێن) is created by Saro Xizirnijad with boundless love for all Kurdish people, and for everyone in Rojhelat who has endured oppression, loss, and suffering under the repression of the Islamic Republic of Iran, the regime of the gallows. May their stories and courage never be forgotten.';
function dedicationMarkup(locale){
 const product='<strong data-no-translate>Kurdistan VPN (کوردستان ڤی‌پی‌ئێن)</strong>',author='<a href="https://github.com/saroo98" target="_blank" rel="noopener noreferrer"><strong data-no-translate>Saro Xizirnijad</strong></a>',place='<a href="https://en.wikipedia.org/wiki/Iranian_Kurdistan" target="_blank" rel="noopener noreferrer"><em data-no-translate>Rojhelat</em></a>';
 const text={en:`${product} is created by ${author} with boundless love for all Kurdish people, and for everyone in ${place} who has endured oppression, loss, and suffering under the repression of the Islamic Republic of Iran, the regime of the gallows. May their stories and courage never be forgotten.`,ckb:`${product} بە دەستی ${author}، بە خۆشەویستییەکی بێسنوور بۆ هەموو گەلی کورد و بۆ هەموو ئەوانەی لە ${place} لەژێر سەرکوتی کۆماری ئیسلامیی ئێران، ڕژێمی سێدارە، ستەم و لەدەستدان و ئازاریان چێشتووە، دروست کراوە. با چیرۆک و ئازایەتییان هەرگیز لەبیر نەکرێن.`,kmr:`${product} ji aliyê ${author} ve, bi evîneke bêpayan ji bo hemû gelê Kurd û ji bo hemû kesên li ${place} yên ku di bin zordariya Komara Îslamî ya Îranê, rejîma darvekirinê de, zilm, windahî û êş kişandine, hatiye çêkirin. Bila çîrok û wêrekiya wan tu carî ji bîr neçin.`};
 return `<blockquote class="dedication" data-no-translate><p>${text[locale]}</p></blockquote>`;
}
function footer(ctx,page){const groups=[['Product',[['How it works','how-it-works'],['Android & releases','download'],['Grandma Mode','simple'],['Help','help']]],['Operate',[['Self-host','self-host'],['Documentation','docs'],['Verify a file','verify'],['Offline reading','offline']]],['Trust & project',[['Security model','trust'],['Privacy','privacy'],['About','about'],['License','license']]]];return `<footer class="site-footer"><section class="wrap principles" aria-label="Four principles">${principles.map(([a,b],i)=>`<div class="principle"><span class="principle-number" aria-hidden="true">0${i+1}</span><h2>${a}</h2><p>${b}</p></div>`).join('')}</section><div class="wrap footer-top"><div class="footer-brand">${brand(ctx)}<p>Free and open-source software.<br>Made for restricted networks.</p>${github()}</div>${groups.map(([title,items])=>`<nav aria-label="${title} footer" class="full-navigation"><h2>${title}</h2>${items.map(([label,to])=>`<a href="${ctx.p(to)}">${label}</a>`).join('')}</nav>`).join('')}<nav class="simple-navigation" aria-label="Simple footer navigation"><a href="${ctx.p('')}">Home</a><a href="${ctx.p('download')}">Android app</a><a href="${ctx.p('help')}">Help</a><a href="${ctx.p('privacy')}">Privacy</a><a href="${ctx.p('trust')}">Security model</a><button data-full-site data-enhance>Use full website</button></nav></div><div class="wrap dedication-wrap"><p class="eyebrow">Creator’s dedication</p>${dedicationMarkup(ctx.locale)}</div><div class="wrap footer-bottom"><p>Source reviewed <time datetime="${config.reviewed}">${config.reviewed}</time></p><nav aria-label="Website information"><a href="${ctx.p('privacy/website')}">Website privacy</a><a href="${ctx.p('accessibility')}">Accessibility</a><a href="${ctx.p('languages')}">Languages</a><a href="#top" data-back-top>Back to top ${icon('up')}</a></nav></div></footer>`;}
function searchDialog(ctx){return `<dialog id="site-search" aria-labelledby="search-dialog-title"><div class="search-dialog-head"><h2 id="search-dialog-title">What do you need?</h2><button type="button" data-search-close aria-label="Close search">${icon('close')}</button></div><label for="global-search">Search the website</label><input id="global-search" type="search" autocomplete="off" placeholder="Profile expired, DNS, self-host…" aria-describedby="global-search-status"><p id="global-search-status" class="caption" role="status">Search runs on this device.</p><div data-global-results></div><div class="search-dialog-foot">${link('Open the full search page',ctx.p('search'))}<kbd>Esc</kbd></div></dialog><div class="sr-only" role="status" id="site-announcer" aria-live="polite"></div>`;}
export function pageBody(page,ctx,pages){
 if(page.custom)return page.custom(ctx);
 const headings=(page.sections||[]).map((s,i)=>`<a href="#${s.id}" data-toc-link>${/^\d{2}\s/.test(s.title)?'':`<span class="toc-number" aria-hidden="true">${String(i+1).padStart(2,'0')}</span>`}${s.title}</a>`).join('');
 const rootLabel=page.category==='Documentation'?'Documentation':page.category;
 const docs=pages.filter(p=>p.category==='Documentation');const position=docs.findIndex(p=>p.slug===page.slug);
 const sequence=position<0?'':`<nav class="doc-sequence" aria-label="Documentation sequence">${[[position-1,'Previous'],[position+1,'Next']].map(([i,label])=>docs[i]?`<a href="${ctx.p(docs[i].slug)}"><small>${label}</small><span>${e(docs[i].title.replace(/ — .*$/,''))}</span>${icon('arrow','directional')}</a>`:'<span></span>').join('')}</nav>`;
 const parent=page.slug.startsWith('docs/')?'docs':page.slug.startsWith('help/')?'help':page.slug.includes('/')?page.slug.split('/')[0]:'';
 return `<div class="wrap page-head"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="${ctx.p('')}">Home</a>${parent?`<span aria-hidden="true">/</span><a href="${ctx.p(parent)}">${e(parent==='docs'?'Documentation':parent[0].toUpperCase()+parent.slice(1))}</a>`:''}<span aria-hidden="true">/</span><span aria-current="page">${e(page.eyebrow?.split('/').at(-1).trim()||rootLabel)}</span></nav><p class="eyebrow">${e(page.eyebrow||rootLabel)}</p><h1>${(page.heading||e(page.title)).replace(/<br\s*\/?>/g,'<br> ')}</h1><p class="page-lede">${e(page.lead||page.description)}</p></div><div class="wrap article-layout"><aside class="article-toc"><nav aria-label="On this page"><p class="eyebrow">On this page</p>${headings}</nav><p class="caption">Source snapshot<br><code dir="ltr">${config.revision.slice(0,12)}</code></p><button data-print data-enhance class="print-button">Print this page ${icon('file')}</button></aside><article class="article-content">${(page.sections||[]).map((s,i)=>`<section id="${s.id}" class="article-section" data-reading-section>${/^\d{2}\s/.test(s.title)?'':`<div class="section-landmark" aria-hidden="true">${String(i+1).padStart(2,'0')}</div>`}<h2>${s.title}<a class="heading-anchor" href="#${s.id}" aria-label="Link to section">#</a></h2>${s.body(ctx)}</section>`).join('')}${page.sources?.length?`<section class="source-review"><h2>Source and scope</h2><p>Reviewed <time datetime="${config.reviewed}">${config.reviewed}</time>. The linked source describes the implementation; released-build evidence is a separate check.</p><div class="source-links">${page.sources.map(k=>link({readme:'Project README',ctl:'kurdctl command implementation',security:'Self-host security',selfhost:'Operator quickstart',strings:'Android UI resources',home:'Android Home source',license:'Project license',mark:'Original brand mark',releases:'Repository releases'}[k],sources[k],'source-link',true)).join('')}</div></section>`:''}${page.related?.length?`<nav class="related-links" aria-label="Continue reading"><h2>Continue from here</h2>${page.related.map((slug,i)=>{const p=pages.find(p=>p.slug===slug);if(!p)throw Error('Missing related page '+slug);return `<div class="related-entry"><span aria-hidden="true">0${i+1}</span>${link(p.heading?.replace(/<br>/g,' ')||p.title,ctx.p(slug))}</div>`;}).join('')}</nav>`:''}${sequence}</article></div>`;
}
export function document(page,ctx,assets,pages,{alias=false,error=false}={}){
 const l=locales[ctx.locale],site=new URL(config.siteUrl),canonical=new URL(ctx.p(page.slug),site.origin).href;
 const title=t(page.title,ctx.locale),description=t(page.description,ctx.locale);
 const social=new URL(ctx.a('social-'+(page.social||'product')+'-'+ctx.locale+'.png'),site.origin).href;
 const structured=JSON.stringify({'@context':'https://schema.org','@type':'WebPage',name:title,description,url:canonical,inLanguage:ctx.locale,isPartOf:{'@type':'WebSite',name:config.name,url:config.siteUrl}}).replace(/</g,'\\u003c');
 const ui=JSON.stringify(Object.fromEntries(clientMessages.map(key=>[key,t(key,ctx.locale)]))).replace(/</g,'\\u003c');
 const body=localizeHTML(`<a class="skip-link" href="#content">Skip to content</a>${header(ctx,page)}<main id="content" tabindex="-1">${pageBody(page,ctx,pages)}</main>${footer(ctx,page)}${searchDialog(ctx)}<noscript><div class="noscript-note wrap">You can read and navigate without JavaScript. Search, manual preferences and the app demo are optional enhancements.</div></noscript>`,ctx.locale);
 return `<!doctype html><html lang="${ctx.locale}" dir="${l.dir}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="light dark"><title>${e(title)}</title><meta name="description" content="${e(description)}"><link rel="canonical" href="${e(canonical)}"><meta name="robots" content="${error||alias?'noindex,follow':'index,follow'}">${Object.keys(locales).map(code=>`<link rel="alternate" hreflang="${locales[code].hreflang}" href="${e(site.origin+ctx.p(page.slug,code))}">`).join('')}<link rel="alternate" hreflang="x-default" href="${e(site.origin+ctx.p(page.slug,'en'))}"><meta property="og:type" content="website"><meta property="og:site_name" content="Kurdistan VPN"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(description)}"><meta property="og:url" content="${e(canonical)}"><meta property="og:image" content="${e(social)}"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="${e(title)}"><meta name="twitter:card" content="summary_large_image"><link rel="icon" type="image/svg+xml" href="${ctx.a('kurdistan-mark.svg')}"><script src="${ctx.base+assets.boot}"></script><link rel="stylesheet" href="${ctx.base+assets.css}">${ctx.locale==='ckb'&&assets.fonts?`<link rel="stylesheet" href="${ctx.base+assets.fonts}">`:''}<script type="application/ld+json">${structured}</script><script type="application/json" id="ui-messages">${ui}</script><script type="module" src="${ctx.base+assets.js}"></script></head><body data-base="${ctx.base}" data-page="${e(page.slug)}" data-locale="${ctx.locale}" data-search-index="${ctx.base}search-index-${ctx.locale}.json"${alias?' data-locale-entry':''}>${body}</body></html>`;
}
