import {escape as e} from '../lib/core.mjs';
import {sun,icon,link,technical} from './primitives.mjs';
import {ownership} from '../content/ownership.mjs';
import {refinementCopy} from '../phase3/refinement.mjs';
export function architecture(ctx,compact=false){
 if(compact){const items=[ownership[0],{id:'kurd',name:'Kurd',owner:'The verified profile',icon:'sun',simple:'The connection follows the rules signed by the deployment owner.',limit:'The app cannot add a relay or fallback that the profile does not permit.'},ownership[4],ownership[1],ownership[2],ownership[3]];
 return `<div class="architecture architecture-hero" data-ownership data-hero-ownership><div class="architecture-meta"><span>YOUR CONNECTION, EXPLAINED</span><span data-no-translate>01 / KURD</span></div><nav class="hero-path" data-owner-nav aria-label="Inspect the ownership path">${items.map((o,i)=>`<a href="#hero-${o.id}" data-owner="${o.id}" class="hero-node ${i<3?'major-node':'minor-node'}">${o.icon==='sun'?sun():icon(o.icon)}<span>${e(o.name)}</span></a>`).join('')}</nav><div class="hero-boundary-panels">${items.map(o=>`<section id="hero-${o.id}" class="ownership-panel"><p class="eyebrow">CONTROLLED BY</p><h2>${e(o.owner)}</h2><p>${e(o.simple)}</p><p class="hero-limit">${e(o.limit)}</p></section>`).join('')}</div><a href="#ownership" class="hero-deeper">See all ownership boundaries ${icon('arrow','directional')}</a></div>`;
 }
 return `<div class="architecture" aria-label="How the phone, profile and VPN server relate"><div class="architecture-meta"><span>PHONE TO SERVER</span><span data-no-translate>01 / KURD</span></div><div class="path-model"><div class="path-end">${icon('phone')}<strong>Your phone</strong><small>You control the device</small></div><span class="path-rule" aria-hidden="true"></span><div class="path-kurd">${sun()}<strong data-no-translate>Kurd</strong><small>Authenticated connection</small></div><span class="path-rule" aria-hidden="true"></span><div class="path-end">${icon('server')}<strong>VPN server</strong><small>You choose the server operator</small></div></div><div class="profile-authorizes">${icon('file')}<div><strong>Your profile contains the connection setup.</strong><small>The profile sets access rules. It is not another server.</small></div></div>${technical('<p>Android imports an explicitly chosen <code dir="ltr">kurd://</code> profile. You compare the deployment identity; the core verifies its policy before opening an authenticated Kurd session to the owner’s relay.</p><p>The app does not receive the owner’s root signing keys. Transport and fallback choices stay inside the signed profile. Public production qualification remains a separate release gate.</p>')}</div>`;
}
export function ownerExplorer(){return `<div class="ownership-explorer" data-ownership id="ownership-explorer"><nav class="ownership-choices" data-owner-nav aria-label="Choose a trust boundary">${ownership.map((o,i)=>`<a href="#owner-${o.id}" data-owner="${o.id}" class="owner-choice">${icon(o.icon)}<span>${e(o.name)}</span><small>${String(i+1).padStart(2,'0')}</small></a>`).join('')}</nav><div class="ownership-panels">${ownership.map((o,i)=>`<section id="owner-${o.id}" class="ownership-panel"><div class="eyebrow">WHO CONTROLS EACH PART? <span aria-hidden="true">/ ${String(i+1).padStart(2,'0')}</span></div><h3>${e(o.owner)}</h3><p class="owner-statement">${e(o.simple)}</p>${technical(`<p>${e(o.technical)}</p>`)}<div class="boundary-note"><span>Where that control ends</span><p>${e(o.limit)}</p></div></section>`).join('')}</div></div>`;}
export function demo(ctx,start='disconnected'){
 const labels=refinementCopy[ctx.locale]||refinementCopy.en;
 return `<div class="product-demo" data-demo data-demo-initial="${start}"><div class="demo-toolbar"><span class="demo-badge">INTERACTIVE APP DEMO</span></div><div class="demo-layout"><div class="demo-instructions"><h3>Try the app’s controls.</h3><p>This sandbox uses the supplied app design. Do not enter real profiles, passwords or server details.</p><div class="demo-actions" data-enhance><div class="demo-control-group"><h4 data-no-translate>${e(labels.demoStates)}</h4><div class="demo-state-controls"><button data-demo-command="disconnected">VPN off</button><button data-demo-command="connecting">Connecting</button><button data-demo-command="connected">VPN on</button><button data-demo-command="attention">Needs attention</button></div></div><div class="demo-control-group"><h4 data-no-translate>${e(labels.demoViews)}</h4><div class="demo-state-controls"><button data-demo-command="profiles">Profiles</button><button data-demo-command="trust">Verify trust</button><button data-demo-command="grandma">Grandma Mode</button></div></div></div><p class="caption" data-no-translate data-demo-notice>${e(labels.demoNote)}</p><noscript><p>The app demo needs JavaScript. The explanations and guides do not.</p></noscript>${link('Read the app workflow',ctx.p('docs/profile'))}<p class="caption" data-demo-feedback role="status"></p></div><div class="demo-viewport" data-demo-host><img class="demo-poster" src="${ctx.a('prototype-home.webp')}" width="432" height="860" alt="Kurdistan VPN app design showing Home with the VPN off" loading="lazy" decoding="async"></div></div>`;
}
export function checksumTool(){return `<form id="checksum-form" class="checksum-form" data-enhance novalidate><label for="checksum-file">File to check <span>(up to 64 MiB; never uploaded)</span></label><input id="checksum-file" name="file" type="file" required aria-describedby="checksum-note checksum-error"><label for="checksum-expected">Expected SHA-256 checksum</label><input id="checksum-expected" name="expected" type="text" dir="ltr" inputmode="text" autocomplete="off" autocapitalize="off" spellcheck="false" maxlength="64" required aria-describedby="checksum-note checksum-error"><p id="checksum-note" class="caption">Get the expected value through a separately trusted channel. Matching bytes does not verify the publisher’s identity.</p><p id="checksum-error" class="field-error" role="alert"></p><button class="button primary" type="submit">Compare checksum ${icon('check')}</button><output id="checksum-output" aria-live="polite"></output></form><noscript><p>Use a local SHA-256 utility to compare the file with a separately authenticated expected value. The browser comparison needs JavaScript.</p></noscript>`;}
