/** Phase 3 composition. Source-bound capabilities and translated copy are build data. */
import {readFileSync} from 'node:fs';
import {escape as e} from '../lib/core.mjs';
import {icon,sun,proof,link} from '../components/primitives.mjs';
import {ownerExplorer,demo} from '../components/experiences.mjs';
import {localizeHTML} from '../i18n/translate.mjs';
import {refinedHero,methodFamilies} from './refinement.mjs';
import {config} from '../../site.config.mjs';
export const phase3Copy=JSON.parse(readFileSync(new URL('./copy.json',import.meta.url),'utf8'));
export const protocolRegistry=JSON.parse(readFileSync(new URL('../content/protocols.json',import.meta.url),'utf8'));
export const privacyRegistry=JSON.parse(readFileSync(new URL('../content/privacy.json',import.meta.url),'utf8'));
export function p3(locale){const copy=phase3Copy[locale];if(!copy)throw Error('Missing Phase 3 locale '+locale);return key=>{if(!copy[key])throw Error('Missing Phase 3 string '+locale+':'+key);return e(copy[key]);};}
function action(label,url,primary=false){return `<a class="button ${primary?'primary':'secondary'}" href="${e(url)}">${label}${icon('arrow','directional')}</a>`;}
function detail(label,body){return `<details class="technical"><summary>${icon('chevron','disclosure-chevron')}<span>${label}</span></summary><div class="detail-body">${body}</div></details>`;}
export function protocolList(locale,{compact=false}={}){const x=p3(locale);return `<div class="protocol-list${compact?' compact-protocols':''}">${protocolRegistry.protocols.map(p=>`<article class="protocol-record" data-protocol-id="${e(p.id)}" data-protocol-status="${p.status}" data-connectable="${p.connectable}"><div class="protocol-record-title">${p.id==='kurd'?sun():icon('file')}<h3 dir="ltr">${e(p.name)}</h3>${p.id==='kurd'?`<span class="protocol-status">${x('implemented')}</span>`:''}</div>${p.id==='kurd'?`<p>${x(p.descriptionKey)}</p>`:''}<a class="source-link" href="${e(p.evidence[0])}" target="_blank" rel="noopener noreferrer">${x('github')}${icon('external')}</a></article>`).join('')}</div>`;}
export function protocolDialog(locale){const x=p3(locale);return `<dialog id="protocol-dialog" class="protocol-dialog" aria-labelledby="protocol-dialog-title" data-no-translate><div class="protocol-dialog-head"><div><h2 id="protocol-dialog-title">${x('protocolTitle')}</h2></div><button type="button" class="icon-button" data-protocol-close aria-label="${x('protocolClose')}">${icon('close')}</button></div><p>${x('protocolNote')}</p><label for="protocol-search">${x('protocolSearch')}</label><input id="protocol-search" type="search" autocomplete="off" data-protocol-search><p class="caption" data-protocol-empty hidden>${x('protocolEmpty')}</p>${protocolList(locale)}<p class="caption">${x('inspected')} <time datetime="${protocolRegistry.reviewed}">${protocolRegistry.reviewed}</time> · <code dir="ltr">${protocolRegistry.revision.slice(0,12)}</code></p></dialog>`;}
function connectionHero(c){return refinedHero(c.locale);}
export function privacyExplorer(locale){const x=p3(locale);return `<div class="privacy-explorer ownership-explorer" data-ownership><nav class="ownership-choices" data-owner-nav aria-label="${x('privacyTitle')}">${privacyRegistry.roles.map((r,i)=>`<a href="#privacy-${r.id}" data-owner="${r.id}" class="owner-choice">${icon(i===0?'phone':i===2||i===3?'server':i===4?'external':'settings')}<span>${x(r.nameKey)}</span><small aria-hidden="true">0${i+1}</small></a>`).join('')}</nav><div class="ownership-panels">${privacyRegistry.roles.map(r=>`<section id="privacy-${r.id}" class="ownership-panel"><p class="eyebrow">${x('privacyMay')}</p><h3>${x(r.nameKey)}</h3><p class="owner-statement">${x(r.visibleKey)}</p><div class="privacy-boundary"><p class="eyebrow">${x('privacyLimit')}</p><p>${x(r.limitKey)}</p></div></section>`).join('')}</div></div>`;}
export function phase3Home(c){const x=p3(c.locale),old=html=>localizeHTML(html,c.locale);return `<div class="phase3-home" data-no-translate>
<section class="hero wrap" aria-labelledby="hero-title"><div class="hero-copy"><h1 id="hero-title">${x('hero')}</h1><p class="hero-lede full-layout">${x('lead')}</p><p class="hero-lede simple-layout">${x('simpleLead')}</p><div class="action-row full-layout">${action(x('how'),'#restricted-networks',true)}${action(x('try'),'#app-demo')}</div><div class="action-row simple-layout">${action(x('help'),c.p('help'),true)}${action(x('android'),c.p('download'))}</div><p class="hero-account">${icon('check')}<span>${x('account')}</span></p><a class="hero-android" href="${c.p('download')}">${x('android')}${icon('arrow','directional')}</a></div><div class="hero-visual full-layout">${connectionHero(c)}</div></section>
<details class="home-more" data-simple-depth open><summary class="simple-layout wrap">${x('details')}${icon('chevron','disclosure-chevron')}</summary><div>
<section id="restricted-networks" class="section wrap editorial p3-major"><div><h2>${x('restrictedTitle')}</h2></div><div class="reading"><p class="large-copy">${x('restrictedBody')}</p><p class="context-note">${x('restrictedLimit')}</p>${detail(x('technical'),`<p>${x('restrictionTech')}</p>`)}${action(x('security'),c.p('trust'))}</div></section>
<section id="protocols" class="section wrap p3-major protocol-section"><div class="section-heading"><div><h2>${x('protocolTitle')}</h2></div><div class="reading"><p>${x('protocolLead')}</p><p class="caption">${x('protocolNote')}</p></div></div>${methodFamilies(c.locale)}</section>
<section id="the-model" class="section wrap editorial p3-major"><div><h2>${x('pathTitle')}</h2></div><div class="reading"><p class="large-copy">${x('pathBody')}</p><p>${x('pathSafety')}</p><div class="action-row">${action(x('profileGuide'),c.p('docs/profile'))}${link(x('hostGuide'),c.p('self-host'))}</div></div></section>
<section class="section wrap p3-major control-section"><div class="section-heading"><div><h2>${x('controlTitle')}</h2></div><p>${x('controlLead')}</p></div>${old(ownerExplorer())}</section>
<section id="privacy-model" class="section wrap p3-major"><div class="section-heading"><div><h2>${x('privacyTitle')}</h2></div><p>${x('privacyLead')}</p></div>${privacyExplorer(c.locale)}<div class="privacy-footer">${action(x('privacyRead'),c.p('privacy'))}</div></section>
<section class="section wrap proof-section p3-major"><div><h2>${x('evidenceTitle')}</h2><p>${x('evidenceBody')}</p>${action(x('security'),c.p('trust'))}</div><div>${old(proof('account')+proof('trust')+proof('storage')+proof('privacy'))}</div></section>
<section id="app-demo" class="section wrap p3-major product-story"><div class="section-heading"><div><h2>${x('demoTitle')}</h2></div><p>${x('demoBody')}</p></div>${old(demo(c,'disconnected'))}<button class="text-link demo-protocol-link" data-protocol-open aria-expanded="false" aria-haspopup="dialog" aria-controls="protocol-dialog">${x('protocolsInDemo')}${icon('arrow','directional')}</button></section>
<section class="section wrap editorial p3-major"><div><h2>${x('hostTitle')}</h2></div><div class="reading"><p class="large-copy">${x('hostBody')}</p><p>${x('hostRecovery')}</p>${action(x('guide'),c.p('self-host'),true)}</div></section>
<section class="section wrap p3-major p3-closing"><div class="foss-statement"><h2>${x('foss')}</h2><p>${x('fossBody')}</p></div><div class="status-statement"><h2>${x('statusTitle')}</h2><p>${x('statusBody')}</p><div class="action-row">${action(x('statusCta'),c.p('download'),true)}${link(x('github'),config.source,'text-link',true)}</div></div></section>
</div></details>${protocolDialog(c.locale)}</div>`;}
